# 03 — MS-TCN-Style Teacher-Student Training on Breakfast

This notebook runs the first controlled training experiment for the updated project direction.

Core idea:

```text
Training:   text can be used
Inference:  only visual features are used
```

Models compared:

```text
1. baseline_visual_only      — visual-only TCN baseline
2. text_aware_teacher        — teacher using CLIP action text prototypes
3. student_ce_only           — video-only student trained without distillation
4. student_kd_video_only     — video-only student trained with KD from teacher
```

Default config is a scale-1 control run: 200 train videos, 50 test videos, 3 epochs.
For full experiments, change `RUN_MODE` below.

## 1. Runtime setup

This notebook can run locally on Linux or in Colab.

For the local Linux setup, it expects this repository structure:

```text
text-assisted-tas/
├── data/
│   ├── zenodo_ms_tcn_data/
│   │   └── breakfast/
│   │       ├── features/
│   │       ├── groundTruth/
│   │       ├── splits/
│   │       └── mapping.txt
│   └── text_assisted_tas/
│       └── breakfast/
│           └── text_embeddings/
│               ├── breakfast_clip_vitb16_text_embedding_config.json
│               ├── breakfast_clip_vitb16_text_embedding_metadata.csv
│               └── breakfast_clip_vitb16_text_embeddings.npy
├── notebooks/
└── runs/
```

In [86]:
try:
    from google.colab import drive
    IN_COLAB = True
    drive.mount('/content/drive')
except Exception:
    IN_COLAB = False
    print('Running outside Colab. Google Drive mount skipped.')

Running outside Colab. Google Drive mount skipped.

## 2. Imports and path configuration

In [87]:
from pathlib import Path
import os
import json
import random
import time
import shutil
import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

from tqdm.auto import tqdm

try:
    from IPython.display import display
except Exception:
    def display(x):
        print(x)


def find_project_root() -> Path:
    """Find the repository root for local runs or fall back to Colab Drive paths."""
    candidates = []

    env_root = os.environ.get('TAS_PROJECT_ROOT')
    if env_root:
        candidates.append(Path(env_root).expanduser().resolve())

    cwd = Path.cwd().resolve()
    candidates.extend([cwd] + list(cwd.parents))

    candidates.extend([
        Path.home() / 'text-assisted-tas',
        Path.home() / 'tas_project_local',
    ])

    for candidate in candidates:
        if (candidate / 'data' / 'zenodo_ms_tcn_data' / 'breakfast').exists():
            return candidate

    colab_root = Path('/content/drive/MyDrive/mmf_tas_lab_project')
    if colab_root.exists():
        return colab_root

    raise FileNotFoundError(
        'Could not find project root. Run the notebook from the repo, or set TAS_PROJECT_ROOT. '
        'Expected data/zenodo_ms_tcn_data/breakfast under the project root.'
    )


PROJECT_ROOT = find_project_root()
DATA_ROOT = PROJECT_ROOT / 'data'

BREAKFAST_ROOT = DATA_ROOT / 'zenodo_ms_tcn_data' / 'breakfast'
TEXT_ASSISTED_ROOT = DATA_ROOT / 'text_assisted_tas' / 'breakfast'
TEXT_EMBEDDING_DIR = TEXT_ASSISTED_ROOT / 'text_embeddings'

RUNS_ROOT = PROJECT_ROOT / 'runs'
RUNS_ROOT.mkdir(parents=True, exist_ok=True)

print('IN_COLAB:', IN_COLAB)
print('PROJECT_ROOT:', PROJECT_ROOT)
print('DATA_ROOT:', DATA_ROOT)
print('BREAKFAST_ROOT:', BREAKFAST_ROOT)
print('TEXT_ASSISTED_ROOT:', TEXT_ASSISTED_ROOT)
print('RUNS_ROOT:', RUNS_ROOT)

IN_COLAB: False
PROJECT_ROOT: /home/mkirilin/text-assisted-tas
DATA_ROOT: /home/mkirilin/text-assisted-tas/data
BREAKFAST_ROOT: /home/mkirilin/text-assisted-tas/data/zenodo_ms_tcn_data/breakfast
TEXT_ASSISTED_ROOT: /home/mkirilin/text-assisted-tas/data/text_assisted_tas/breakfast
RUNS_ROOT: /home/mkirilin/text-assisted-tas/runs

## 3. Experiment configuration

In [88]:
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

device = 'cuda' if torch.cuda.is_available() else 'cpu'

# Options:
#   'local_debug'    -> very small local test
#   'scale1_control' -> current recommended controlled proof-of-concept
#   'full_split1'    -> full Breakfast split 1
RUN_MODE = 'full_split1'
SPLIT_ID = 1

if RUN_MODE == 'local_debug':
    RUN_NAME = 'mstcn_teacher_student_split1_local_debug'
    MAX_TRAIN_VIDEOS = 20
    MAX_TEST_VIDEOS = 10
    NUM_EPOCHS_BASELINE = 1
    NUM_EPOCHS_TEACHER = 1
    NUM_EPOCHS_STUDENT = 1
elif RUN_MODE == 'scale1_control':
    RUN_NAME = 'mstcn_teacher_student_split1_scale1_control'
    MAX_TRAIN_VIDEOS = 200
    MAX_TEST_VIDEOS = 50
    NUM_EPOCHS_BASELINE = 3
    NUM_EPOCHS_TEACHER = 3
    NUM_EPOCHS_STUDENT = 3
elif RUN_MODE == 'full_split1':
    RUN_NAME = 'mstcn_teacher_student_split1_full'
    MAX_TRAIN_VIDEOS = None
    MAX_TEST_VIDEOS = None
    NUM_EPOCHS_BASELINE = 10
    NUM_EPOCHS_TEACHER = 10
    NUM_EPOCHS_STUDENT = 10
else:
    raise ValueError(f'Unknown RUN_MODE: {RUN_MODE}')

BATCH_SIZE = 1
LEARNING_RATE = 5e-4
WEIGHT_DECAY = 1e-5

NUM_F_MAPS = 64
NUM_LAYERS = 8
NUM_STAGES = 2

KD_TEMPERATURE = 4.0
LAMBDA_CE = 1.0
LAMBDA_KD = 1.0

COPY_SELECTED_DATA_TO_LOCAL = False

RUN_ROOT = RUNS_ROOT / RUN_NAME
LOCAL_RUN_ROOT = RUN_ROOT
RUN_ROOT.mkdir(parents=True, exist_ok=True)

print('Device:', device)
if device == 'cuda':
    print('GPU:', torch.cuda.get_device_name(0))
print('RUN_MODE:', RUN_MODE)
print('RUN_NAME:', RUN_NAME)
print('Split:', SPLIT_ID)
print('MAX_TRAIN_VIDEOS:', MAX_TRAIN_VIDEOS)
print('MAX_TEST_VIDEOS:', MAX_TEST_VIDEOS)
print('Epochs baseline/teacher/student:', NUM_EPOCHS_BASELINE, NUM_EPOCHS_TEACHER, NUM_EPOCHS_STUDENT)
print('COPY_SELECTED_DATA_TO_LOCAL:', COPY_SELECTED_DATA_TO_LOCAL)
print('RUN_ROOT:', RUN_ROOT)

if device != 'cuda':
    print('\nWARNING: CUDA is not available. The notebook will run on CPU and may be slow.')

Device: cpu
RUN_MODE: full_split1
RUN_NAME: mstcn_teacher_student_split1_full
Split: 1
MAX_TRAIN_VIDEOS: None
MAX_TEST_VIDEOS: None
Epochs baseline/teacher/student: 10 10 10
COPY_SELECTED_DATA_TO_LOCAL: False
RUN_ROOT: /home/mkirilin/text-assisted-tas/runs/mstcn_teacher_student_split1_full

WARNING: CUDA is not available. The notebook will run on CPU and may be slow.

## 4. Validate required files

In [89]:
required_paths = {
    'Breakfast features': BREAKFAST_ROOT / 'features',
    'Breakfast groundTruth': BREAKFAST_ROOT / 'groundTruth',
    'Breakfast mapping': BREAKFAST_ROOT / 'mapping.txt',
    'Breakfast splits': BREAKFAST_ROOT / 'splits',
    'Text embeddings': TEXT_EMBEDDING_DIR / 'breakfast_clip_vitb16_text_embeddings.npy',
    'Text embedding metadata': TEXT_EMBEDDING_DIR / 'breakfast_clip_vitb16_text_embedding_metadata.csv',
}

for name, path in required_paths.items():
    print(f'{name}: {path} -> exists={path.exists()}')
    if not path.exists():
        raise FileNotFoundError(f'Missing required file/folder: {name}: {path}')

print('\nFile counts:')
print('features .npy:', len(list((BREAKFAST_ROOT / 'features').glob('*.npy'))))
print('groundTruth .txt:', len(list((BREAKFAST_ROOT / 'groundTruth').glob('*.txt'))))
print('split .bundle:', len(list((BREAKFAST_ROOT / 'splits').glob('*.bundle'))))

Breakfast features: /home/mkirilin/text-assisted-tas/data/zenodo_ms_tcn_data/breakfast/features -> exists=True
Breakfast groundTruth: /home/mkirilin/text-assisted-tas/data/zenodo_ms_tcn_data/breakfast/groundTruth -> exists=True
Breakfast mapping: /home/mkirilin/text-assisted-tas/data/zenodo_ms_tcn_data/breakfast/mapping.txt -> exists=True
Breakfast splits: /home/mkirilin/text-assisted-tas/data/zenodo_ms_tcn_data/breakfast/splits -> exists=True
Text embeddings: /home/mkirilin/text-assisted-tas/data/text_assisted_tas/breakfast/text_embeddings/breakfast_clip_vitb16_text_embeddings.npy -> exists=True
Text embedding metadata: /home/mkirilin/text-assisted-tas/data/text_assisted_tas/breakfast/text_embeddings/breakfast_clip_vitb16_text_embedding_metadata.csv -> exists=True

File counts:
features .npy: 1712
groundTruth .txt: 1712
split .bundle: 8

## 5. Load mapping, text embeddings, and splits

In [90]:
def read_lines(path: Path):
    return path.read_text().splitlines()


def load_mapping(mapping_path: Path):
    idx_to_label = {}
    label_to_idx = {}
    for line in read_lines(mapping_path):
        line = line.strip()
        if not line:
            continue
        idx, label = line.split(maxsplit=1)
        idx = int(idx)
        idx_to_label[idx] = label
        label_to_idx[label] = idx
    return idx_to_label, label_to_idx


def load_split(split_path: Path):
    video_ids = []
    for line in read_lines(split_path):
        line = line.strip()
        if line:
            video_ids.append(Path(line).stem)
    return video_ids


idx_to_label, label_to_idx = load_mapping(BREAKFAST_ROOT / 'mapping.txt')
num_classes = len(idx_to_label)

text_embeddings = np.load(TEXT_EMBEDDING_DIR / 'breakfast_clip_vitb16_text_embeddings.npy').astype(np.float32)
text_metadata = pd.read_csv(TEXT_EMBEDDING_DIR / 'breakfast_clip_vitb16_text_embedding_metadata.csv')

train_ids = load_split(BREAKFAST_ROOT / 'splits' / f'train.split{SPLIT_ID}.bundle')
test_ids = load_split(BREAKFAST_ROOT / 'splits' / f'test.split{SPLIT_ID}.bundle')

if MAX_TRAIN_VIDEOS is not None:
    train_ids = train_ids[:MAX_TRAIN_VIDEOS]
if MAX_TEST_VIDEOS is not None:
    test_ids = test_ids[:MAX_TEST_VIDEOS]

print('Number of classes:', num_classes)
print('Text embeddings shape:', text_embeddings.shape)
print('Train videos:', len(train_ids))
print('Test videos:', len(test_ids))
display(text_metadata.head())

Number of classes: 48
Text embeddings shape: (48, 512)
Train videos: 1460
Test videos: 252

,class_index,action_label,action_text,prompt
0,0,SIL,SIL,a video of the action: SIL
1,1,pour_cereals,pour cereals,a video of the action: pour cereals
2,2,pour_milk,pour milk,a video of the action: pour milk
3,3,stir_cereals,stir cereals,a video of the action: stir cereals
4,4,take_bowl,take bowl,a video of the action: take bowl

## 6. Optional local data cache

In [91]:
ACTIVE_FEATURE_DIR = BREAKFAST_ROOT / 'features'
ACTIVE_GT_DIR = BREAKFAST_ROOT / 'groundTruth'

if COPY_SELECTED_DATA_TO_LOCAL:
    selected_ids = sorted(set(train_ids + test_ids))
    LOCAL_DATA_CACHE = PROJECT_ROOT / '.cache' / 'breakfast_selected_cache' / RUN_NAME
    local_feature_dir = LOCAL_DATA_CACHE / 'features'
    local_gt_dir = LOCAL_DATA_CACHE / 'groundTruth'
    local_feature_dir.mkdir(parents=True, exist_ok=True)
    local_gt_dir.mkdir(parents=True, exist_ok=True)

    for video_id in tqdm(selected_ids, desc='Copying selected Breakfast files to local cache'):
        src_feature = BREAKFAST_ROOT / 'features' / f'{video_id}.npy'
        dst_feature = local_feature_dir / f'{video_id}.npy'
        if not dst_feature.exists():
            shutil.copy2(src_feature, dst_feature)

        src_gt = BREAKFAST_ROOT / 'groundTruth' / f'{video_id}.txt'
        dst_gt = local_gt_dir / f'{video_id}.txt'
        if not dst_gt.exists():
            shutil.copy2(src_gt, dst_gt)

    ACTIVE_FEATURE_DIR = local_feature_dir
    ACTIVE_GT_DIR = local_gt_dir

print('ACTIVE_FEATURE_DIR:', ACTIVE_FEATURE_DIR)
print('ACTIVE_GT_DIR:', ACTIVE_GT_DIR)

ACTIVE_FEATURE_DIR: /home/mkirilin/text-assisted-tas/data/zenodo_ms_tcn_data/breakfast/features
ACTIVE_GT_DIR: /home/mkirilin/text-assisted-tas/data/zenodo_ms_tcn_data/breakfast/groundTruth

## 7. Dataset and DataLoader

In [92]:
class BreakfastTASDataset(Dataset):
    def __init__(self, video_ids, feature_dir: Path, gt_dir: Path, label_to_idx: dict):
        self.video_ids = list(video_ids)
        self.feature_dir = feature_dir
        self.gt_dir = gt_dir
        self.label_to_idx = label_to_idx

    def __len__(self):
        return len(self.video_ids)

    def __getitem__(self, index):
        video_id = self.video_ids[index]
        feature_path = self.feature_dir / f'{video_id}.npy'
        gt_path = self.gt_dir / f'{video_id}.txt'

        features = np.load(feature_path).astype(np.float32)
        labels_str = read_lines(gt_path)
        labels = np.asarray([self.label_to_idx[x] for x in labels_str], dtype=np.int64)

        T = min(features.shape[1], len(labels))
        features = features[:, :T]
        labels = labels[:T]

        return {
            'video_id': video_id,
            'features': torch.from_numpy(features),
            'labels': torch.from_numpy(labels),
            'length': T,
        }


def tas_collate_fn(batch):
    batch_size = len(batch)
    feature_dim = batch[0]['features'].shape[0]
    max_len = max(item['length'] for item in batch)

    features = torch.zeros(batch_size, feature_dim, max_len, dtype=torch.float32)
    labels = torch.full((batch_size, max_len), fill_value=-100, dtype=torch.long)
    mask = torch.zeros(batch_size, 1, max_len, dtype=torch.float32)
    video_ids = []

    for i, item in enumerate(batch):
        T = item['length']
        features[i, :, :T] = item['features']
        labels[i, :T] = item['labels']
        mask[i, :, :T] = 1.0
        video_ids.append(item['video_id'])

    return {
        'video_ids': video_ids,
        'features': features,
        'labels': labels,
        'mask': mask,
        'lengths': torch.tensor([item['length'] for item in batch], dtype=torch.long),
    }


train_dataset = BreakfastTASDataset(train_ids, ACTIVE_FEATURE_DIR, ACTIVE_GT_DIR, label_to_idx)
test_dataset = BreakfastTASDataset(test_ids, ACTIVE_FEATURE_DIR, ACTIVE_GT_DIR, label_to_idx)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, collate_fn=tas_collate_fn, num_workers=0)
test_loader = DataLoader(test_dataset, batch_size=1, shuffle=False, collate_fn=tas_collate_fn, num_workers=0)

sample = next(iter(train_loader))
print('Sample features:', sample['features'].shape)
print('Sample labels:', sample['labels'].shape)
print('Sample mask:', sample['mask'].shape)
print('Sample video:', sample['video_ids'][0])

Sample features: torch.Size([1, 2048, 1249])
Sample labels: torch.Size([1, 1249])
Sample mask: torch.Size([1, 1, 1249])
Sample video: P48_cam01_P48_juice

## 8. MS-TCN-style model definitions

In [93]:
class DilatedResidualLayer(nn.Module):
    def __init__(self, dilation, channels):
        super().__init__()
        self.conv_dilated = nn.Conv1d(channels, channels, kernel_size=3, padding=dilation, dilation=dilation)
        self.conv_1x1 = nn.Conv1d(channels, channels, kernel_size=1)
        self.dropout = nn.Dropout(0.5)

    def forward(self, x, mask):
        out = F.relu(self.conv_dilated(x))
        out = self.conv_1x1(out)
        out = self.dropout(out)
        return (x + out) * mask


class SingleStageTCN(nn.Module):
    def __init__(self, num_layers, num_f_maps, dim, num_classes):
        super().__init__()
        self.conv_in = nn.Conv1d(dim, num_f_maps, kernel_size=1)
        self.layers = nn.ModuleList([DilatedResidualLayer(2 ** i, num_f_maps) for i in range(num_layers)])
        self.conv_out = nn.Conv1d(num_f_maps, num_classes, kernel_size=1)

    def forward(self, x, mask):
        out = self.conv_in(x) * mask
        for layer in self.layers:
            out = layer(out, mask)
        return self.conv_out(out) * mask


class MultiStageTCN(nn.Module):
    def __init__(self, num_stages, num_layers, num_f_maps, dim, num_classes):
        super().__init__()
        self.stage1 = SingleStageTCN(num_layers, num_f_maps, dim, num_classes)
        self.stages = nn.ModuleList([
            SingleStageTCN(num_layers, num_f_maps, num_classes, num_classes)
            for _ in range(num_stages - 1)
        ])

    def forward(self, x, mask):
        outputs = []
        out = self.stage1(x, mask)
        outputs.append(out)
        for stage in self.stages:
            out = stage(F.softmax(out, dim=1) * mask, mask)
            outputs.append(out)
        return torch.stack(outputs, dim=0)

## 9. Text-aware teacher model

In [94]:
class TextPrototypeSingleStageTCN(nn.Module):
    def __init__(self, num_layers, num_f_maps, dim, text_embeddings_np):
        super().__init__()
        text_embeddings_t = torch.from_numpy(text_embeddings_np).float()
        text_embeddings_t = F.normalize(text_embeddings_t, dim=1)
        self.register_buffer('text_embeddings', text_embeddings_t)  # [C, E]

        num_classes, text_dim = text_embeddings_t.shape
        self.conv_in = nn.Conv1d(dim, num_f_maps, kernel_size=1)
        self.layers = nn.ModuleList([DilatedResidualLayer(2 ** i, num_f_maps) for i in range(num_layers)])
        self.visual_to_text = nn.Conv1d(num_f_maps, text_dim, kernel_size=1)
        self.logit_scale = nn.Parameter(torch.tensor(10.0))

    def forward(self, x, mask):
        out = self.conv_in(x) * mask
        for layer in self.layers:
            out = layer(out, mask)
        projected = self.visual_to_text(out)  # [B, E, T]
        projected = F.normalize(projected, dim=1)
        logits = torch.einsum('bet,ce->bct', projected, self.text_embeddings)
        logits = logits * self.logit_scale.clamp(1.0, 100.0)
        return logits * mask


class TextPrototypeMultiStageTCN(nn.Module):
    def __init__(self, num_stages, num_layers, num_f_maps, dim, text_embeddings_np):
        super().__init__()
        num_classes = text_embeddings_np.shape[0]
        self.stage1 = TextPrototypeSingleStageTCN(num_layers, num_f_maps, dim, text_embeddings_np)
        self.stages = nn.ModuleList([
            TextPrototypeSingleStageTCN(num_layers, num_f_maps, num_classes, text_embeddings_np)
            for _ in range(num_stages - 1)
        ])

    def forward(self, x, mask):
        outputs = []
        out = self.stage1(x, mask)
        outputs.append(out)
        for stage in self.stages:
            out = stage(F.softmax(out, dim=1) * mask, mask)
            outputs.append(out)
        return torch.stack(outputs, dim=0)

## 10. Losses and metrics

In [95]:
def mstcn_supervised_loss(outputs, labels):
    total_loss = 0.0
    for s in range(outputs.shape[0]):
        logits = outputs[s].transpose(1, 2).contiguous()
        total_loss = total_loss + F.cross_entropy(
            logits.view(-1, logits.shape[-1]),
            labels.view(-1),
            ignore_index=-100,
        )
    return total_loss / outputs.shape[0]


def kd_loss_student_teacher(student_outputs, teacher_outputs, labels, temperature=4.0, lambda_ce=1.0, lambda_kd=1.0):
    ce = mstcn_supervised_loss(student_outputs, labels)
    student_last = student_outputs[-1]
    teacher_last = teacher_outputs[-1].detach()
    valid = labels != -100

    s_logits = student_last.transpose(1, 2)[valid]
    t_logits = teacher_last.transpose(1, 2)[valid]

    log_p_student = F.log_softmax(s_logits / temperature, dim=-1)
    p_teacher = F.softmax(t_logits / temperature, dim=-1)
    kd = F.kl_div(log_p_student, p_teacher, reduction='batchmean') * (temperature ** 2)
    return lambda_ce * ce + lambda_kd * kd, ce.detach(), kd.detach()


@torch.no_grad()
def framewise_accuracy(model, loader, device):
    model.eval()
    correct = 0
    total = 0
    for batch in loader:
        features = batch['features'].to(device)
        labels = batch['labels'].to(device)
        mask = batch['mask'].to(device)
        outputs = model(features, mask)
        preds = torch.argmax(outputs[-1], dim=1)
        valid = labels != -100
        correct += (preds[valid] == labels[valid]).sum().item()
        total += valid.sum().item()
    return correct / max(total, 1)

## 11. Build models

In [96]:
feature_dim = sample['features'].shape[1]

baseline_model = MultiStageTCN(NUM_STAGES, NUM_LAYERS, NUM_F_MAPS, feature_dim, num_classes).to(device)
teacher_model = TextPrototypeMultiStageTCN(NUM_STAGES, NUM_LAYERS, NUM_F_MAPS, feature_dim, text_embeddings).to(device)
student_ce_model = MultiStageTCN(NUM_STAGES, NUM_LAYERS, NUM_F_MAPS, feature_dim, num_classes).to(device)
student_kd_model = MultiStageTCN(NUM_STAGES, NUM_LAYERS, NUM_F_MAPS, feature_dim, num_classes).to(device)

print('Feature dim:', feature_dim)
print('Classes:', num_classes)
print('Baseline parameters:', sum(p.numel() for p in baseline_model.parameters()))
print('Teacher parameters:', sum(p.numel() for p in teacher_model.parameters()))
print('Student CE-only parameters:', sum(p.numel() for p in student_ce_model.parameters()))
print('Student KD parameters:', sum(p.numel() for p in student_kd_model.parameters()))

Feature dim: 2048
Classes: 48
Baseline parameters: 404704
Teacher parameters: 465026
Student CE-only parameters: 404704
Student KD parameters: 404704

## 12. Training loops

In [97]:
def train_supervised_model(model, loader, optimizer, num_epochs, device, model_name):
    history = []
    for epoch in range(1, num_epochs + 1):
        model.train()
        epoch_losses = []
        start_time = time.time()

        for batch in tqdm(loader, desc=f'{model_name} epoch {epoch}/{num_epochs}'):
            features = batch['features'].to(device)
            labels = batch['labels'].to(device)
            mask = batch['mask'].to(device)

            optimizer.zero_grad()
            outputs = model(features, mask)
            loss = mstcn_supervised_loss(outputs, labels)
            loss.backward()
            optimizer.step()
            epoch_losses.append(float(loss.item()))

        row = {
            'model': model_name,
            'epoch': epoch,
            'loss': float(np.mean(epoch_losses)) if epoch_losses else float('nan'),
            'train_acc': framewise_accuracy(model, train_loader, device),
            'test_acc': framewise_accuracy(model, test_loader, device),
            'seconds': time.time() - start_time,
        }
        history.append(row)
        print(row)
    return pd.DataFrame(history)


def train_student_with_kd(student, teacher, loader, optimizer, num_epochs, device):
    history = []
    teacher.eval()
    for epoch in range(1, num_epochs + 1):
        student.train()
        epoch_losses, epoch_ce, epoch_kd = [], [], []
        start_time = time.time()

        for batch in tqdm(loader, desc=f'student KD epoch {epoch}/{num_epochs}'):
            features = batch['features'].to(device)
            labels = batch['labels'].to(device)
            mask = batch['mask'].to(device)

            optimizer.zero_grad()
            with torch.no_grad():
                teacher_outputs = teacher(features, mask)
            student_outputs = student(features, mask)
            loss, ce, kd = kd_loss_student_teacher(
                student_outputs,
                teacher_outputs,
                labels,
                temperature=KD_TEMPERATURE,
                lambda_ce=LAMBDA_CE,
                lambda_kd=LAMBDA_KD,
            )
            loss.backward()
            optimizer.step()

            epoch_losses.append(float(loss.item()))
            epoch_ce.append(float(ce.item()))
            epoch_kd.append(float(kd.item()))

        row = {
            'model': 'student_kd_video_only',
            'epoch': epoch,
            'loss': float(np.mean(epoch_losses)) if epoch_losses else float('nan'),
            'ce': float(np.mean(epoch_ce)) if epoch_ce else float('nan'),
            'kd': float(np.mean(epoch_kd)) if epoch_kd else float('nan'),
            'train_acc': framewise_accuracy(student, train_loader, device),
            'test_acc': framewise_accuracy(student, test_loader, device),
            'seconds': time.time() - start_time,
        }
        history.append(row)
        print(row)
    return pd.DataFrame(history)

## 13. Train models

In [98]:
def save_single_model_checkpoint(model_name, model, history_df):
    path = RUN_ROOT / f'{model_name}_checkpoint.pt'
    payload = {
        'model_name': model_name,
        'run_mode': RUN_MODE,
        'run_name': RUN_NAME,
        'split_id': SPLIT_ID,
        'state_dict': model.state_dict(),
        'history': history_df.to_dict(orient='records'),
        'config': {
            'max_train_videos': MAX_TRAIN_VIDEOS,
            'max_test_videos': MAX_TEST_VIDEOS,
            'num_classes': num_classes,
            'feature_dim': feature_dim,
            'num_stages': NUM_STAGES,
            'num_layers': NUM_LAYERS,
            'num_f_maps': NUM_F_MAPS,
        },
    }
    torch.save(payload, path, _use_new_zipfile_serialization=False)
    print(f'Saved checkpoint: {path}')


baseline_optimizer = torch.optim.Adam(baseline_model.parameters(), lr=LEARNING_RATE, weight_decay=WEIGHT_DECAY)
baseline_history = train_supervised_model(
    baseline_model, train_loader, baseline_optimizer, NUM_EPOCHS_BASELINE, device, 'baseline_visual_only'
)
display(baseline_history)
save_single_model_checkpoint('baseline_visual_only', baseline_model, baseline_history)

teacher_optimizer = torch.optim.Adam(teacher_model.parameters(), lr=LEARNING_RATE, weight_decay=WEIGHT_DECAY)
teacher_history = train_supervised_model(
    teacher_model, train_loader, teacher_optimizer, NUM_EPOCHS_TEACHER, device, 'text_aware_teacher'
)
display(teacher_history)
save_single_model_checkpoint('text_aware_teacher', teacher_model, teacher_history)

student_ce_optimizer = torch.optim.Adam(student_ce_model.parameters(), lr=LEARNING_RATE, weight_decay=WEIGHT_DECAY)
student_ce_history = train_supervised_model(
    student_ce_model, train_loader, student_ce_optimizer, NUM_EPOCHS_STUDENT, device, 'student_ce_only'
)
display(student_ce_history)
save_single_model_checkpoint('student_ce_only', student_ce_model, student_ce_history)

student_kd_optimizer = torch.optim.Adam(student_kd_model.parameters(), lr=LEARNING_RATE, weight_decay=WEIGHT_DECAY)
student_kd_history = train_student_with_kd(
    student_kd_model, teacher_model, train_loader, student_kd_optimizer, NUM_EPOCHS_STUDENT, device
)
display(student_kd_history)
save_single_model_checkpoint('student_kd_video_only', student_kd_model, student_kd_history)

baseline_visual_only epoch 1/10: 100%|██████████| 1460/1460 [07:42<00:00,  3.16it/s]

{'model': 'baseline_visual_only', 'epoch': 1, 'loss': 2.6819297861971267, 'train_acc': 0.31748543256034645, 'test_acc': 0.3144639528948087, 'seconds': 631.1980998516083}

baseline_visual_only epoch 2/10: 100%|██████████| 1460/1460 [07:46<00:00,  3.13it/s]

{'model': 'baseline_visual_only', 'epoch': 2, 'loss': 1.9177095300122484, 'train_acc': 0.3431586104838895, 'test_acc': 0.3390414346823051, 'seconds': 673.4216916561127}

baseline_visual_only epoch 3/10: 100%|██████████| 1460/1460 [08:16<00:00,  2.94it/s]

{'model': 'baseline_visual_only', 'epoch': 3, 'loss': 1.6184341175098942, 'train_acc': 0.45476015539898695, 'test_acc': 0.4105836311043049, 'seconds': 704.371279001236}

baseline_visual_only epoch 4/10: 100%|██████████| 1460/1460 [08:01<00:00,  3.03it/s]

{'model': 'baseline_visual_only', 'epoch': 4, 'loss': 1.4290628439759554, 'train_acc': 0.5601519635375665, 'test_acc': 0.46774576492515163, 'seconds': 680.8529117107391}

baseline_visual_only epoch 5/10: 100%|██████████| 1460/1460 [08:15<00:00,  2.94it/s]

{'model': 'baseline_visual_only', 'epoch': 5, 'loss': 1.3028260067258388, 'train_acc': 0.4995250329203556, 'test_acc': 0.4340274068006537, 'seconds': 690.7702074050903}

baseline_visual_only epoch 6/10: 100%|██████████| 1460/1460 [08:02<00:00,  3.03it/s]

{'model': 'baseline_visual_only', 'epoch': 6, 'loss': 1.2005604181081464, 'train_acc': 0.520896120761879, 'test_acc': 0.43562607088729816, 'seconds': 673.8162579536438}

baseline_visual_only epoch 7/10: 100%|██████████| 1460/1460 [08:05<00:00,  3.01it/s]

{'model': 'baseline_visual_only', 'epoch': 7, 'loss': 1.1059360477614075, 'train_acc': 0.589293648923651, 'test_acc': 0.4941454863460633, 'seconds': 661.7736053466797}

baseline_visual_only epoch 8/10: 100%|██████████| 1460/1460 [07:43<00:00,  3.15it/s]

{'model': 'baseline_visual_only', 'epoch': 8, 'loss': 1.0390270267243256, 'train_acc': 0.6106825622099922, 'test_acc': 0.5130920300263938, 'seconds': 659.4732534885406}

baseline_visual_only epoch 9/10: 100%|██████████| 1460/1460 [07:42<00:00,  3.16it/s]

{'model': 'baseline_visual_only', 'epoch': 9, 'loss': 0.9718399636753617, 'train_acc': 0.5907264905880031, 'test_acc': 0.4985497267629822, 'seconds': 620.5934453010559}

baseline_visual_only epoch 10/10: 100%|██████████| 1460/1460 [07:10<00:00,  3.39it/s]

{'model': 'baseline_visual_only', 'epoch': 10, 'loss': 0.9108150196606166, 'train_acc': 0.666812295149178, 'test_acc': 0.5330416958502004, 'seconds': 603.8596041202545}

                  model  epoch      loss  train_acc  test_acc     seconds
0  baseline_visual_only      1  2.681930   0.317485  0.314464  631.198100
1  baseline_visual_only      2  1.917710   0.343159  0.339041  673.421692
2  baseline_visual_only      3  1.618434   0.454760  0.410584  704.371279
3  baseline_visual_only      4  1.429063   0.560152  0.467746  680.852912
4  baseline_visual_only      5  1.302826   0.499525  0.434027  690.770207
5  baseline_visual_only      6  1.200560   0.520896  0.435626  673.816258
6  baseline_visual_only      7  1.105936   0.589294  0.494145  661.773605
7  baseline_visual_only      8  1.039027   0.610683  0.513092  659.473253
8  baseline_visual_only      9  0.971840   0.590726  0.498550  620.593445
9  baseline_visual_only     10  0.910815   0.666812  0.533042  603.859604

Saved checkpoint: /home/mkirilin/text-assisted-tas/runs/mstcn_teacher_student_split1_full/baseline_visual_only_checkpoint.pt

text_aware_teacher epoch 1/10: 100%|██████████| 1460/1460 [08:14<00:00,  2.95it/s]

{'model': 'text_aware_teacher', 'epoch': 1, 'loss': 3.0300378191144497, 'train_acc': 0.1961323970329385, 'test_acc': 0.21246008286145043, 'seconds': 731.5959045886993}

text_aware_teacher epoch 2/10: 100%|██████████| 1460/1460 [09:41<00:00,  2.51it/s]

{'model': 'text_aware_teacher', 'epoch': 2, 'loss': 2.473635633922603, 'train_acc': 0.3395500922547794, 'test_acc': 0.3028360459180645, 'seconds': 805.8205072879791}

text_aware_teacher epoch 3/10: 100%|██████████| 1460/1460 [07:52<00:00,  3.09it/s]

{'model': 'text_aware_teacher', 'epoch': 3, 'loss': 2.204889813188004, 'train_acc': 0.4221259792246061, 'test_acc': 0.40815397825975125, 'seconds': 620.18798661232}

text_aware_teacher epoch 4/10: 100%|██████████| 1460/1460 [06:23<00:00,  3.81it/s]

{'model': 'text_aware_teacher', 'epoch': 4, 'loss': 2.044399934762145, 'train_acc': 0.43979293963299676, 'test_acc': 0.38327971477300155, 'seconds': 536.9185082912445}

text_aware_teacher epoch 5/10: 100%|██████████| 1460/1460 [06:21<00:00,  3.83it/s]

{'model': 'text_aware_teacher', 'epoch': 5, 'loss': 1.9173764045107855, 'train_acc': 0.4645178038922345, 'test_acc': 0.3966249985160915, 'seconds': 528.5591995716095}

text_aware_teacher epoch 6/10: 100%|██████████| 1460/1460 [06:22<00:00,  3.82it/s]

{'model': 'text_aware_teacher', 'epoch': 6, 'loss': 1.7688321899469586, 'train_acc': 0.5000678987398058, 'test_acc': 0.4190616949796408, 'seconds': 530.5389399528503}

text_aware_teacher epoch 7/10: 100%|██████████| 1460/1460 [06:14<00:00,  3.90it/s]

{'model': 'text_aware_teacher', 'epoch': 7, 'loss': 1.6610631247497585, 'train_acc': 0.5041628895629428, 'test_acc': 0.4350602071140552, 'seconds': 511.98697543144226}

text_aware_teacher epoch 8/10: 100%|██████████| 1460/1460 [06:03<00:00,  4.02it/s]

{'model': 'text_aware_teacher', 'epoch': 8, 'loss': 1.5810029605684215, 'train_acc': 0.5275806625685429, 'test_acc': 0.46275983237769625, 'seconds': 496.41393423080444}

text_aware_teacher epoch 9/10: 100%|██████████| 1460/1460 [05:57<00:00,  4.09it/s]

{'model': 'text_aware_teacher', 'epoch': 9, 'loss': 1.4839910439840736, 'train_acc': 0.5569213447385931, 'test_acc': 0.4787365805208321, 'seconds': 492.007351398468}

text_aware_teacher epoch 10/10: 100%|██████████| 1460/1460 [05:55<00:00,  4.11it/s]

{'model': 'text_aware_teacher', 'epoch': 10, 'loss': 1.3853671588309824, 'train_acc': 0.44047063063506875, 'test_acc': 0.40425426673156295, 'seconds': 471.06028509140015}

                model  epoch      loss  train_acc  test_acc     seconds
0  text_aware_teacher      1  3.030038   0.196132  0.212460  731.595905
1  text_aware_teacher      2  2.473636   0.339550  0.302836  805.820507
2  text_aware_teacher      3  2.204890   0.422126  0.408154  620.187987
3  text_aware_teacher      4  2.044400   0.439793  0.383280  536.918508
4  text_aware_teacher      5  1.917376   0.464518  0.396625  528.559200
5  text_aware_teacher      6  1.768832   0.500068  0.419062  530.538940
6  text_aware_teacher      7  1.661063   0.504163  0.435060  511.986975
7  text_aware_teacher      8  1.581003   0.527581  0.462760  496.413934
8  text_aware_teacher      9  1.483991   0.556921  0.478737  492.007351
9  text_aware_teacher     10  1.385367   0.440471  0.404254  471.060285

Saved checkpoint: /home/mkirilin/text-assisted-tas/runs/mstcn_teacher_student_split1_full/text_aware_teacher_checkpoint.pt

student_ce_only epoch 1/10: 100%|██████████| 1460/1460 [04:56<00:00,  4.92it/s]

{'model': 'student_ce_only', 'epoch': 1, 'loss': 2.699009963788398, 'train_acc': 0.3003256870817705, 'test_acc': 0.3082038375852258, 'seconds': 399.1783037185669}

student_ce_only epoch 2/10: 100%|██████████| 1460/1460 [04:58<00:00,  4.89it/s]

{'model': 'student_ce_only', 'epoch': 2, 'loss': 1.9268259692477854, 'train_acc': 0.4171688850702825, 'test_acc': 0.36639283608548895, 'seconds': 413.03921818733215}

student_ce_only epoch 3/10: 100%|██████████| 1460/1460 [05:06<00:00,  4.76it/s]

{'model': 'student_ce_only', 'epoch': 3, 'loss': 1.6247161436162583, 'train_acc': 0.44688941126444953, 'test_acc': 0.38259118123073393, 'seconds': 421.61783146858215}

student_ce_only epoch 4/10: 100%|██████████| 1460/1460 [05:07<00:00,  4.74it/s]

{'model': 'student_ce_only', 'epoch': 4, 'loss': 1.4500185518844486, 'train_acc': 0.5375473549146534, 'test_acc': 0.4264812374609732, 'seconds': 435.63451766967773}

student_ce_only epoch 5/10: 100%|██████████| 1460/1460 [05:14<00:00,  4.64it/s]

{'model': 'student_ce_only', 'epoch': 5, 'loss': 1.2833354043123657, 'train_acc': 0.5291862489981289, 'test_acc': 0.4426894753295266, 'seconds': 436.94593620300293}

student_ce_only epoch 6/10: 100%|██████████| 1460/1460 [05:19<00:00,  4.57it/s]

{'model': 'student_ce_only', 'epoch': 6, 'loss': 1.1575743088371133, 'train_acc': 0.539823826267381, 'test_acc': 0.43762835808492706, 'seconds': 440.51007866859436}

student_ce_only epoch 7/10: 100%|██████████| 1460/1460 [05:13<00:00,  4.66it/s]

{'model': 'student_ce_only', 'epoch': 7, 'loss': 1.0569800378116843, 'train_acc': 0.6120437779960765, 'test_acc': 0.4667109860670885, 'seconds': 437.87299370765686}

student_ce_only epoch 8/10: 100%|██████████| 1460/1460 [05:12<00:00,  4.68it/s]

{'model': 'student_ce_only', 'epoch': 8, 'loss': 0.9974805664883493, 'train_acc': 0.6011961845769714, 'test_acc': 0.4938269406555314, 'seconds': 423.9087595939636}

student_ce_only epoch 9/10: 100%|██████████| 1460/1460 [05:01<00:00,  4.84it/s]

{'model': 'student_ce_only', 'epoch': 9, 'loss': 0.937224751052587, 'train_acc': 0.6321424531766077, 'test_acc': 0.5037315352319448, 'seconds': 412.0014293193817}

student_ce_only epoch 10/10: 100%|██████████| 1460/1460 [04:57<00:00,  4.91it/s]

{'model': 'student_ce_only', 'epoch': 10, 'loss': 0.9018057304549298, 'train_acc': 0.7058302492612973, 'test_acc': 0.5435279825571503, 'seconds': 391.3285367488861}

             model  epoch      loss  train_acc  test_acc     seconds
0  student_ce_only      1  2.699010   0.300326  0.308204  399.178304
1  student_ce_only      2  1.926826   0.417169  0.366393  413.039218
2  student_ce_only      3  1.624716   0.446889  0.382591  421.617831
3  student_ce_only      4  1.450019   0.537547  0.426481  435.634518
4  student_ce_only      5  1.283335   0.529186  0.442689  436.945936
5  student_ce_only      6  1.157574   0.539824  0.437628  440.510079
6  student_ce_only      7  1.056980   0.612044  0.466711  437.872994
7  student_ce_only      8  0.997481   0.601196  0.493827  423.908760
8  student_ce_only      9  0.937225   0.632142  0.503732  412.001429
9  student_ce_only     10  0.901806   0.705830  0.543528  391.328537

Saved checkpoint: /home/mkirilin/text-assisted-tas/runs/mstcn_teacher_student_split1_full/student_ce_only_checkpoint.pt

student KD epoch 1/10: 100%|██████████| 1460/1460 [06:00<00:00,  4.05it/s]

{'model': 'student_kd_video_only', 'epoch': 1, 'loss': 3.6514120180312903, 'ce': 2.74468255957512, 'kd': 0.906729464579935, 'train_acc': 0.2693126540888167, 'test_acc': 0.2999790274265861, 'seconds': 466.3240797519684}

student KD epoch 2/10: 100%|██████████| 1460/1460 [06:08<00:00,  3.97it/s]

{'model': 'student_kd_video_only', 'epoch': 2, 'loss': 2.4874850952053724, 'ce': 1.9722066850694893, 'kd': 0.5152784113606361, 'train_acc': 0.408037071739637, 'test_acc': 0.3827514433483307, 'seconds': 486.40199518203735}

student KD epoch 3/10: 100%|██████████| 1460/1460 [06:13<00:00,  3.91it/s]

{'model': 'student_kd_video_only', 'epoch': 3, 'loss': 2.070892511144893, 'ce': 1.6908836459460324, 'kd': 0.3800088676381601, 'train_acc': 0.4515107388582057, 'test_acc': 0.40914522913525725, 'seconds': 495.2256121635437}

student KD epoch 4/10: 100%|██████████| 1460/1460 [06:04<00:00,  4.01it/s]

{'model': 'student_kd_video_only', 'epoch': 4, 'loss': 1.8105632048559515, 'ce': 1.5027437131290566, 'kd': 0.3078194943090824, 'train_acc': 0.5180939608365255, 'test_acc': 0.45383066031949537, 'seconds': 477.50150537490845}

student KD epoch 5/10: 100%|██████████| 1460/1460 [06:03<00:00,  4.01it/s]

{'model': 'student_kd_video_only', 'epoch': 5, 'loss': 1.6561434143822487, 'ce': 1.382716986771724, 'kd': 0.2734264271155204, 'train_acc': 0.5579315613112656, 'test_acc': 0.47717748732742143, 'seconds': 475.98753666877747}

student KD epoch 6/10: 100%|██████████| 1460/1460 [06:03<00:00,  4.01it/s]

{'model': 'student_kd_video_only', 'epoch': 6, 'loss': 1.500524232893774, 'ce': 1.2589738426347301, 'kd': 0.24155039128477443, 'train_acc': 0.4907581550599794, 'test_acc': 0.4151046056562635, 'seconds': 476.171103477478}

student KD epoch 7/10: 100%|██████████| 1460/1460 [06:11<00:00,  3.93it/s]

{'model': 'student_kd_video_only', 'epoch': 7, 'loss': 1.3966172189336934, 'ce': 1.1746569380368272, 'kd': 0.22196028173633225, 'train_acc': 0.5937240822083587, 'test_acc': 0.47271586911531355, 'seconds': 481.52277398109436}

student KD epoch 8/10: 100%|██████████| 1460/1460 [06:03<00:00,  4.02it/s]

{'model': 'student_kd_video_only', 'epoch': 8, 'loss': 1.3279118683648437, 'ce': 1.1085652093977145, 'kd': 0.21934665990610644, 'train_acc': 0.6051006051900565, 'test_acc': 0.5104546299923628, 'seconds': 475.23344898223877}

student KD epoch 9/10: 100%|██████████| 1460/1460 [06:03<00:00,  4.02it/s]

{'model': 'student_kd_video_only', 'epoch': 9, 'loss': 1.2869717127452158, 'ce': 1.0686161010436817, 'kd': 0.21835561226287933, 'train_acc': 0.5757634881089698, 'test_acc': 0.4755273810795731, 'seconds': 468.140291929245}

student KD epoch 10/10: 100%|██████████| 1460/1460 [06:01<00:00,  4.04it/s]

{'model': 'student_kd_video_only', 'epoch': 10, 'loss': 1.2161223082305634, 'ce': 1.0067427009037913, 'kd': 0.20937960658171406, 'train_acc': 0.5906444935418413, 'test_acc': 0.4836136931118946, 'seconds': 467.2203803062439}

,model,epoch,loss,ce,kd,train_acc,test_acc,seconds
0,student_kd_video_only,1,3.651412,2.744683,0.906729,0.269313,0.299979,466.324080
1,student_kd_video_only,2,2.487485,1.972207,0.515278,0.408037,0.382751,486.401995
2,student_kd_video_only,3,2.070893,1.690884,0.380009,0.451511,0.409145,495.225612
3,student_kd_video_only,4,1.810563,1.502744,0.307819,0.518094,0.453831,477.501505
4,student_kd_video_only,5,1.656143,1.382717,0.273426,0.557932,0.477177,475.987537
5,student_kd_video_only,6,1.500524,1.258974,0.241550,0.490758,0.415105,476.171103
6,student_kd_video_only,7,1.396617,1.174657,0.221960,0.593724,0.472716,481.522774
7,student_kd_video_only,8,1.327912,1.108565,0.219347,0.605101,0.510455,475.233449
8,student_kd_video_only,9,1.286972,1.068616,0.218356,0.575763,0.475527,468.140292
9,student_kd_video_only,10,1.216122,1.006743,0.209380,0.590644,0.483614,467.220380

Saved checkpoint: /home/mkirilin/text-assisted-tas/runs/mstcn_teacher_student_split1_full/student_kd_video_only_checkpoint.pt

In [99]:
for name in [
    "baseline_model",
    "teacher_model",
    "student_ce_model",
    "student_kd_model",
    "train_loader",
    "test_loader",
    "device"
]:
    print(name, name in globals())

baseline_model True
teacher_model True
student_ce_model True
student_kd_model True
train_loader True
test_loader True
device True

## 14. Compare and save results

In [100]:
comparison_rows = []
for name, model in [
    ('baseline_visual_only', baseline_model),
    ('text_aware_teacher', teacher_model),
    ('student_ce_only', student_ce_model),
    ('student_kd_video_only', student_kd_model),
]:
    comparison_rows.append({
        'model': name,
        'train_acc': framewise_accuracy(model, train_loader, device),
        'test_acc': framewise_accuracy(model, test_loader, device),
        'uses_text_at_training': name in ['text_aware_teacher', 'student_kd_video_only'],
        'uses_text_at_inference': name == 'text_aware_teacher',
    })

df_comparison = pd.DataFrame(comparison_rows)
display(df_comparison)

comparison_path = RUN_ROOT / 'comparison.csv'
df_comparison.to_csv(comparison_path, index=False)
print('Saved comparison:', comparison_path)

,model,train_acc,test_acc,uses_text_at_training,uses_text_at_inference
0,baseline_visual_only,0.666812,0.533042,False,False
1,text_aware_teacher,0.440471,0.404254,True,True
2,student_ce_only,0.705830,0.543528,False,False
3,student_kd_video_only,0.590644,0.483614,True,False

Saved comparison: /home/mkirilin/text-assisted-tas/runs/mstcn_teacher_student_split1_full/comparison.csv

## 15. Save checkpoint and summary

In [101]:
checkpoint = {
    'config': {
        'run_mode': RUN_MODE,
        'run_name': RUN_NAME,
        'dataset': 'breakfast',
        'split_id': SPLIT_ID,
        'max_train_videos': MAX_TRAIN_VIDEOS,
        'max_test_videos': MAX_TEST_VIDEOS,
        'num_classes': num_classes,
        'feature_dim': feature_dim,
        'num_stages': NUM_STAGES,
        'num_layers': NUM_LAYERS,
        'num_f_maps': NUM_F_MAPS,
        'kd_temperature': KD_TEMPERATURE,
        'lambda_ce': LAMBDA_CE,
        'lambda_kd': LAMBDA_KD,
    },
    'idx_to_label': idx_to_label,
    'baseline_state_dict': baseline_model.state_dict(),
    'teacher_state_dict': teacher_model.state_dict(),
    'student_ce_state_dict': student_ce_model.state_dict(),
    'student_kd_state_dict': student_kd_model.state_dict(),
    'baseline_history': baseline_history.to_dict(orient='records'),
    'teacher_history': teacher_history.to_dict(orient='records'),
    'student_ce_history': student_ce_history.to_dict(orient='records'),
    'student_kd_history': student_kd_history.to_dict(orient='records'),
    'comparison': df_comparison.to_dict(orient='records'),
}

ckpt_path = RUN_ROOT / 'teacher_student_checkpoint.pt'
torch.save(checkpoint, ckpt_path, _use_new_zipfile_serialization=False)
print('Saved combined checkpoint:', ckpt_path)

summary = {
    'status': 'completed_run',
    'run_mode': RUN_MODE,
    'run_name': RUN_NAME,
    'dataset': 'Breakfast',
    'split': SPLIT_ID,
    'train_videos': len(train_ids),
    'test_videos': len(test_ids),
    'classes': num_classes,
    'feature_dim': feature_dim,
    'text_embedding_shape': list(text_embeddings.shape),
    'models': {
        'baseline_visual_only': 'visual-only MS-TCN-style model',
        'text_aware_teacher': 'teacher with CLIP action text prototypes',
        'student_ce_only': 'video-only student trained with cross entropy only',
        'student_kd_video_only': 'video-only student trained with KD from teacher',
    },
    'comparison': df_comparison.to_dict(orient='records'),
}

summary_path = RUN_ROOT / 'experiment_summary.json'
with summary_path.open('w') as f:
    json.dump(summary, f, indent=2)
print(json.dumps(summary, indent=2))
print('Saved summary:', summary_path)

print('\n03_mstcn_teacher_student_training_LOCAL completed.')

Saved combined checkpoint: /home/mkirilin/text-assisted-tas/runs/mstcn_teacher_student_split1_full/teacher_student_checkpoint.pt
{
  "status": "completed_run",
  "run_mode": "full_split1",
  "run_name": "mstcn_teacher_student_split1_full",
  "dataset": "Breakfast",
  "split": 1,
  "train_videos": 1460,
  "test_videos": 252,
  "classes": 48,
  "feature_dim": 2048,
  "text_embedding_shape": [
    48,
    512
  ],
  "models": {
    "baseline_visual_only": "visual-only MS-TCN-style model",
    "text_aware_teacher": "teacher with CLIP action text prototypes",
    "student_ce_only": "video-only student trained with cross entropy only",
    "student_kd_video_only": "video-only student trained with KD from teacher"
  },
  "comparison": [
    {
      "model": "baseline_visual_only",
      "train_acc": 0.666812295149178,
      "test_acc": 0.5330416958502004,
      "uses_text_at_training": false,
      "uses_text_at_inference": false
    },
    {
      "model": "text_aware_teacher",
      "train_acc": 0.44047063063506875,
      "test_acc": 0.40425426673156295,
      "uses_text_at_training": true,
      "uses_text_at_inference": true
    },
    {
      "model": "student_ce_only",
      "train_acc": 0.7058302492612973,
      "test_acc": 0.5435279825571503,
      "uses_text_at_training": false,
      "uses_text_at_inference": false
    },
    {
      "model": "student_kd_video_only",
      "train_acc": 0.5906444935418413,
      "test_acc": 0.4836136931118946,
      "uses_text_at_training": true,
      "uses_text_at_inference": false
    }
  ]
}
Saved summary: /home/mkirilin/text-assisted-tas/runs/mstcn_teacher_student_split1_full/experiment_summary.json

03_mstcn_teacher_student_training_LOCAL completed.

## 16. Next steps after this notebook

After the scale-1 control run is complete:

1. Add TAS metrics: Edit, F1@10, F1@25, F1@50;
2. Move the same pipeline to Assembly101;
3. Later compare against LTContext.