# 12 — MS-TCN Baseline on Breakfast ProcedureVRL Features

This notebook trains and evaluates a visual-only MS-TCN-style TAS model on the full Breakfast split-1 ProcedureVRL feature dataset produced by notebook 11.

Input dataset:

```text
/content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/runs/procedurevrl_breakfast_full_split1_split1_views16/mstcn_format
```

Expected structure:

```text
features/*.npy       # shape [9871, 16]
groundTruth/*.txt    # length 16
splits/*.bundle
mapping.txt
```

Important limitation:

These are **coarse clip-level ProcedureVRL features**, not dense frame-level I3D features.  
So this run is a **pipeline validation and ProcedureVRL-feature baseline**, not yet a direct paper-level comparison to frame-level I3D MS-TCN results.

## 1. Mount Drive and imports

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

from pathlib import Path
import os
import sys
import json
import time
import random
import shutil
from collections import defaultdict

import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

from tqdm.auto import tqdm

print("Python:", sys.version)
print("Torch:", torch.__version__)
print("CUDA:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU")

Mounted at /content/drive
Python: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
Torch: 2.11.0+cu128
CUDA: True
GPU: Tesla T4

## 2. Paths and configuration

In [ ]:
DRIVE_ROOT = Path("/content/drive/MyDrive/mmf_tas_lab_data")

PROC_RUN_ROOT = (
    DRIVE_ROOT
    / "text_assisted_tas"
    / "breakfast"
    / "procedurevrl"
    / "runs"
    / "procedurevrl_breakfast_full_split1_split1_views16"
)

DATA_ROOT = PROC_RUN_ROOT / "mstcn_format"
FEATURE_DIR = DATA_ROOT / "features"
GT_DIR = DATA_ROOT / "groundTruth"
SPLIT_DIR = DATA_ROOT / "splits"
MAPPING_PATH = DATA_ROOT / "mapping.txt"

RUN_NAME = "mstcn_on_procedurevrl_breakfast_full_split1"
OUT_ROOT = DRIVE_ROOT / "text_assisted_tas" / "breakfast" / "procedurevrl" / "mstcn_runs" / RUN_NAME
PRED_DIR = OUT_ROOT / "predictions"
CKPT_DIR = OUT_ROOT / "checkpoints"
for p in [OUT_ROOT, PRED_DIR, CKPT_DIR]:
    p.mkdir(parents=True, exist_ok=True)

SPLIT_ID = 1
SEED = 42

# Start with a moderate setup
NUM_EPOCHS = 80
BATCH_SIZE = 32
LEARNING_RATE = 5e-4
WEIGHT_DECAY = 1e-4

# Coarse features have T=16, so a very deep/dilated MS-TCN is unnecessary.
NUM_STAGES = 3
NUM_LAYERS = 4
NUM_F_MAPS = 64
DROPOUT = 0.5

# Temporal smoothing loss, as in MS-TCN-style training.
LAMBDA_SMOOTH = 0.15
MAX_SMOOTH_CLAMP = 16.0

device = "cuda" if torch.cuda.is_available() else "cpu"

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

for p in [DATA_ROOT, FEATURE_DIR, GT_DIR, SPLIT_DIR, MAPPING_PATH]:
    assert p.exists(), f"Missing path: {p}"

print("DATA_ROOT:", DATA_ROOT)
print("OUT_ROOT:", OUT_ROOT)
print("device:", device)

DATA_ROOT: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/runs/procedurevrl_breakfast_full_split1_split1_views16/mstcn_format
OUT_ROOT: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1
device: cuda

## 3. Load mapping and split files

In [ ]:
def read_lines(path):
    return [x.strip() for x in Path(path).read_text().splitlines() if x.strip()]

def load_mapping(mapping_path):
    id_to_label = {}
    label_to_id = {}
    for line in read_lines(mapping_path):
        idx, label = line.split()[:2]
        idx = int(idx)
        id_to_label[idx] = label
        label_to_id[label] = idx
    return id_to_label, label_to_id

def load_split_ids(path):
    return [Path(x).stem for x in read_lines(path)]

id_to_label, label_to_id = load_mapping(MAPPING_PATH)
num_classes = len(id_to_label)

train_ids = load_split_ids(SPLIT_DIR / f"train.split{SPLIT_ID}.bundle")
test_ids = load_split_ids(SPLIT_DIR / f"test.split{SPLIT_ID}.bundle")

print("num_classes:", num_classes)
print("train videos:", len(train_ids))
print("test videos:", len(test_ids))
print("first train ids:", train_ids[:5])
print("first labels:", list(label_to_id.items())[:10])

num_classes: 48
train videos: 1460
test videos: 252
first train ids: ['P16_cam01_P16_cereals', 'P16_cam01_P16_friedegg', 'P16_cam01_P16_juice', 'P16_cam01_P16_milk', 'P16_cam01_P16_pancake']
first labels: [('SIL', 0), ('pour_cereals', 1), ('pour_milk', 2), ('stir_cereals', 3), ('take_bowl', 4), ('pour_coffee', 5), ('take_cup', 6), ('spoon_sugar', 7), ('stir_coffee', 8), ('pour_sugar', 9)]

## 4. Validate feature/label dataset

In [ ]:
validation_rows = []

for video_id in train_ids + test_ids:
    feat_path = FEATURE_DIR / f"{video_id}.npy"
    gt_path = GT_DIR / f"{video_id}.txt"

    assert feat_path.exists(), feat_path
    assert gt_path.exists(), gt_path

    feat = np.load(feat_path, mmap_mode="r")
    labels = read_lines(gt_path)

    unknown_labels = sorted(set(labels) - set(label_to_id))
    validation_rows.append({
        "video_id": video_id,
        "split": "train" if video_id in set(train_ids) else "test",
        "feature_shape": list(feat.shape),
        "feature_dim": int(feat.shape[0]),
        "feature_len": int(feat.shape[1]),
        "gt_len": len(labels),
        "length_match": int(feat.shape[1]) == len(labels),
        "unknown_labels": ",".join(unknown_labels),
    })

df_val = pd.DataFrame(validation_rows)
display(df_val.head())

print("videos:", len(df_val))
print("length mismatches:", int((~df_val["length_match"]).sum()))
print("unknown-label rows:", int((df_val["unknown_labels"] != "").sum()))
print("feature_dim unique:", sorted(df_val["feature_dim"].unique().tolist()))
print("feature_len unique:", sorted(df_val["feature_len"].unique().tolist()))

assert df_val["length_match"].all()
assert (df_val["unknown_labels"] == "").all()

feature_dim = int(df_val["feature_dim"].iloc[0])
feature_len = int(df_val["feature_len"].iloc[0])

print("feature_dim:", feature_dim)
print("feature_len:", feature_len)

,video_id,split,feature_shape,feature_dim,feature_len,gt_len,length_match,unknown_labels
0,P16_cam01_P16_cereals,train,"[9871, 16]",9871,16,16,True,
1,P16_cam01_P16_friedegg,train,"[9871, 16]",9871,16,16,True,
2,P16_cam01_P16_juice,train,"[9871, 16]",9871,16,16,True,
3,P16_cam01_P16_milk,train,"[9871, 16]",9871,16,16,True,
4,P16_cam01_P16_pancake,train,"[9871, 16]",9871,16,16,True,

videos: 1712
length mismatches: 0
unknown-label rows: 0
feature_dim unique: [9871]
feature_len unique: [16]
feature_dim: 9871
feature_len: 16

## 5. Dataset and DataLoader

In [ ]:
class ProcedureVRLBreakfastDataset(Dataset):
    def __init__(self, video_ids, feature_dir, gt_dir, label_to_id):
        self.video_ids = list(video_ids)
        self.feature_dir = Path(feature_dir)
        self.gt_dir = Path(gt_dir)
        self.label_to_id = dict(label_to_id)

    def __len__(self):
        return len(self.video_ids)

    def __getitem__(self, idx):
        video_id = self.video_ids[idx]

        feat = np.load(self.feature_dir / f"{video_id}.npy").astype(np.float32)  # [D, T]
        labels = read_lines(self.gt_dir / f"{video_id}.txt")
        y = np.array([self.label_to_id[x] for x in labels], dtype=np.int64)      # [T]

        if feat.shape[1] != len(y):
            raise ValueError(f"Length mismatch for {video_id}: feat {feat.shape}, labels {len(y)}")

        return {
            "video_id": video_id,
            "features": torch.from_numpy(feat),
            "labels": torch.from_numpy(y),
        }

def collate_batch(batch):
    # Here all T=16, but keep padding logic for safety.
    video_ids = [b["video_id"] for b in batch]
    lengths = [b["features"].shape[1] for b in batch]
    max_len = max(lengths)
    dim = batch[0]["features"].shape[0]

    x = torch.zeros(len(batch), dim, max_len, dtype=torch.float32)
    y = torch.full((len(batch), max_len), -100, dtype=torch.long)
    mask = torch.zeros(len(batch), max_len, dtype=torch.bool)

    for i, b in enumerate(batch):
        T = b["features"].shape[1]
        x[i, :, :T] = b["features"]
        y[i, :T] = b["labels"]
        mask[i, :T] = True

    return video_ids, x, y, mask

train_ds = ProcedureVRLBreakfastDataset(train_ids, FEATURE_DIR, GT_DIR, label_to_id)
test_ds = ProcedureVRLBreakfastDataset(test_ids, FEATURE_DIR, GT_DIR, label_to_id)

train_loader = DataLoader(
    train_ds,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=0,
    collate_fn=collate_batch,
    pin_memory=torch.cuda.is_available(),
)

test_loader = DataLoader(
    test_ds,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=0,
    collate_fn=collate_batch,
    pin_memory=torch.cuda.is_available(),
)

video_ids, x, y, mask = next(iter(train_loader))
print("batch x:", x.shape)
print("batch y:", y.shape)
print("batch mask:", mask.shape)
print("first video:", video_ids[0])

batch x: torch.Size([32, 9871, 16])
batch y: torch.Size([32, 16])
batch mask: torch.Size([32, 16])
first video: P48_cam01_P48_juice

## 6. MS-TCN-style model

In [ ]:
class DilatedResidualLayer(nn.Module):
    def __init__(self, dilation, channels, dropout):
        super().__init__()
        self.conv_dilated = nn.Conv1d(channels, channels, kernel_size=3, padding=dilation, dilation=dilation)
        self.conv_1x1 = nn.Conv1d(channels, channels, kernel_size=1)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = F.relu(self.conv_dilated(x))
        out = self.conv_1x1(out)
        out = self.dropout(out)
        return x + out

class SingleStageModel(nn.Module):
    def __init__(self, num_layers, in_dim, num_f_maps, num_classes, dropout):
        super().__init__()
        self.conv_in = nn.Conv1d(in_dim, num_f_maps, kernel_size=1)
        self.layers = nn.ModuleList([
            DilatedResidualLayer(2 ** i, num_f_maps, dropout)
            for i in range(num_layers)
        ])
        self.conv_out = nn.Conv1d(num_f_maps, num_classes, kernel_size=1)

    def forward(self, x):
        out = self.conv_in(x)
        for layer in self.layers:
            out = layer(out)
        return self.conv_out(out)

class MultiStageModel(nn.Module):
    def __init__(self, num_stages, num_layers, in_dim, num_f_maps, num_classes, dropout):
        super().__init__()
        self.stage1 = SingleStageModel(num_layers, in_dim, num_f_maps, num_classes, dropout)
        self.stages = nn.ModuleList([
            SingleStageModel(num_layers, num_classes, num_f_maps, num_classes, dropout)
            for _ in range(num_stages - 1)
        ])

    def forward(self, x):
        outputs = []
        out = self.stage1(x)
        outputs.append(out)
        for stage in self.stages:
            out = stage(F.softmax(out, dim=1))
            outputs.append(out)
        return outputs  # list of [B, C, T]

model = MultiStageModel(
    num_stages=NUM_STAGES,
    num_layers=NUM_LAYERS,
    in_dim=feature_dim,
    num_f_maps=NUM_F_MAPS,
    num_classes=num_classes,
    dropout=DROPOUT,
).to(device)

n_params = sum(p.numel() for p in model.parameters())
print(model)
print("parameters:", n_params)

MultiStageModel(
  (stage1): SingleStageModel(
    (conv_in): Conv1d(9871, 64, kernel_size=(1,), stride=(1,))
    (layers): ModuleList(
      (0): DilatedResidualLayer(
        (conv_dilated): Conv1d(64, 64, kernel_size=(3,), stride=(1,), padding=(1,))
        (conv_1x1): Conv1d(64, 64, kernel_size=(1,), stride=(1,))
        (dropout): Dropout(p=0.5, inplace=False)
      )
      (1): DilatedResidualLayer(
        (conv_dilated): Conv1d(64, 64, kernel_size=(3,), stride=(1,), padding=(2,), dilation=(2,))
        (conv_1x1): Conv1d(64, 64, kernel_size=(1,), stride=(1,))
        (dropout): Dropout(p=0.5, inplace=False)
      )
      (2): DilatedResidualLayer(
        (conv_dilated): Conv1d(64, 64, kernel_size=(3,), stride=(1,), padding=(4,), dilation=(4,))
        (conv_1x1): Conv1d(64, 64, kernel_size=(1,), stride=(1,))
        (dropout): Dropout(p=0.5, inplace=False)
      )
      (3): DilatedResidualLayer(
        (conv_dilated): Conv1d(64, 64, kernel_size=(3,), stride=(1,), padding=(8,), dilation=(8,))
        (conv_1x1): Conv1d(64, 64, kernel_size=(1,), stride=(1,))
        (dropout): Dropout(p=0.5, inplace=False)
      )
    )
    (conv_out): Conv1d(64, 48, kernel_size=(1,), stride=(1,))
  )
  (stages): ModuleList(
    (0-1): 2 x SingleStageModel(
      (conv_in): Conv1d(48, 64, kernel_size=(1,), stride=(1,))
      (layers): ModuleList(
        (0): DilatedResidualLayer(
          (conv_dilated): Conv1d(64, 64, kernel_size=(3,), stride=(1,), padding=(1,))
          (conv_1x1): Conv1d(64, 64, kernel_size=(1,), stride=(1,))
          (dropout): Dropout(p=0.5, inplace=False)
        )
        (1): DilatedResidualLayer(
          (conv_dilated): Conv1d(64, 64, kernel_size=(3,), stride=(1,), padding=(2,), dilation=(2,))
          (conv_1x1): Conv1d(64, 64, kernel_size=(1,), stride=(1,))
          (dropout): Dropout(p=0.5, inplace=False)
        )
        (2): DilatedResidualLayer(
          (conv_dilated): Conv1d(64, 64, kernel_size=(3,), stride=(1,), padding=(4,), dilation=(4,))
          (conv_1x1): Conv1d(64, 64, kernel_size=(1,), stride=(1,))
          (dropout): Dropout(p=0.5, inplace=False)
        )
        (3): DilatedResidualLayer(
          (conv_dilated): Conv1d(64, 64, kernel_size=(3,), stride=(1,), padding=(8,), dilation=(8,))
          (conv_1x1): Conv1d(64, 64, kernel_size=(1,), stride=(1,))
          (dropout): Dropout(p=0.5, inplace=False)
        )
      )
      (conv_out): Conv1d(64, 48, kernel_size=(1,), stride=(1,))
    )
  )
)
parameters: 845584

## 7. Loss, metrics, and evaluation functions

In [ ]:
ce_loss_fn = nn.CrossEntropyLoss(ignore_index=-100)

def mstcn_loss(outputs, targets):
    total = 0.0
    for out in outputs:
        ce = ce_loss_fn(out.transpose(1, 2).reshape(-1, out.shape[1]), targets.reshape(-1))

        # Temporal smoothing on log-probabilities.
        logp = F.log_softmax(out, dim=1)
        smooth = torch.mean(torch.clamp((logp[:, :, 1:] - logp.detach()[:, :, :-1]) ** 2, max=MAX_SMOOTH_CLAMP))

        total = total + ce + LAMBDA_SMOOTH * smooth
    return total

def frame_accuracy_from_logits(logits, targets, mask):
    pred = logits.argmax(dim=1)  # [B, T]
    correct = ((pred == targets) & mask).sum().item()
    total = mask.sum().item()
    return correct / max(total, 1)

def collapse_segments(labels, background=None):
    seg_labels = []
    seg_starts = []
    seg_ends = []

    prev = None
    start = 0

    for i, lab in enumerate(labels):
        if lab != prev:
            if prev is not None and prev != background:
                seg_labels.append(prev)
                seg_starts.append(start)
                seg_ends.append(i)
            prev = lab
            start = i

    if prev is not None and prev != background:
        seg_labels.append(prev)
        seg_starts.append(start)
        seg_ends.append(len(labels))

    return seg_labels, seg_starts, seg_ends

def edit_score(recognized, ground_truth, background=None):
    # Standard Levenshtein on collapsed segment labels.
    P, _, _ = collapse_segments(recognized, background)
    Y, _, _ = collapse_segments(ground_truth, background)

    m, n = len(P), len(Y)
    if n == 0:
        return 100.0 if m == 0 else 0.0

    D = np.zeros((m + 1, n + 1), dtype=np.float32)
    for i in range(m + 1):
        D[i, 0] = i
    for j in range(n + 1):
        D[0, j] = j

    for i in range(1, m + 1):
        for j in range(1, n + 1):
            if P[i - 1] == Y[j - 1]:
                D[i, j] = D[i - 1, j - 1]
            else:
                D[i, j] = min(D[i - 1, j] + 1, D[i, j - 1] + 1, D[i - 1, j - 1] + 1)

    return (1.0 - D[m, n] / max(m, n)) * 100.0

def f_score(recognized, ground_truth, overlap, background=None):
    p_label, p_start, p_end = collapse_segments(recognized, background)
    y_label, y_start, y_end = collapse_segments(ground_truth, background)

    tp = 0
    fp = 0
    hits = np.zeros(len(y_label), dtype=np.float32)

    for j in range(len(p_label)):
        intersection = np.minimum(p_end[j], y_end) - np.maximum(p_start[j], y_start)
        union = np.maximum(p_end[j], y_end) - np.minimum(p_start[j], y_start)
        IoU = (intersection / np.maximum(union, 1e-8)) * ([p_label[j] == y for y in y_label])

        idx = np.array(IoU).argmax() if len(IoU) else -1
        if len(IoU) and IoU[idx] >= overlap and not hits[idx]:
            tp += 1
            hits[idx] = 1
        else:
            fp += 1

    fn = len(y_label) - hits.sum()
    precision = tp / float(tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / float(tp + fn) if (tp + fn) > 0 else 0.0

    if precision + recall == 0:
        return 0.0

    return 2.0 * (precision * recall) / (precision + recall) * 100.0

@torch.no_grad()
def evaluate_model(model, loader, save_predictions=False, pred_dir=None):
    model.eval()

    total_correct = 0
    total_frames = 0
    edit_scores = []
    f1_10 = []
    f1_25 = []
    f1_50 = []

    if save_predictions:
        pred_dir = Path(pred_dir)
        pred_dir.mkdir(parents=True, exist_ok=True)

    for video_ids, x, y, mask in loader:
        x = x.to(device)
        y = y.to(device)
        mask = mask.to(device)

        outputs = model(x)
        logits = outputs[-1]
        pred = logits.argmax(dim=1)  # [B, T]

        total_correct += ((pred == y) & mask).sum().item()
        total_frames += mask.sum().item()

        pred_np = pred.cpu().numpy()
        y_np = y.cpu().numpy()
        mask_np = mask.cpu().numpy()

        for i, vid in enumerate(video_ids):
            T = int(mask_np[i].sum())
            pred_ids = pred_np[i, :T].tolist()
            true_ids = y_np[i, :T].tolist()

            pred_labels = [id_to_label[int(k)] for k in pred_ids]
            true_labels = [id_to_label[int(k)] for k in true_ids]

            edit_scores.append(edit_score(pred_labels, true_labels))
            f1_10.append(f_score(pred_labels, true_labels, 0.10))
            f1_25.append(f_score(pred_labels, true_labels, 0.25))
            f1_50.append(f_score(pred_labels, true_labels, 0.50))

            if save_predictions:
                (pred_dir / f"{vid}.txt").write_text("\n".join(pred_labels) + "\n")

    return {
        "acc": 100.0 * total_correct / max(total_frames, 1),
        "edit": float(np.mean(edit_scores)) if edit_scores else 0.0,
        "f1@10": float(np.mean(f1_10)) if f1_10 else 0.0,
        "f1@25": float(np.mean(f1_25)) if f1_25 else 0.0,
        "f1@50": float(np.mean(f1_50)) if f1_50 else 0.0,
        "frames": int(total_frames),
        "videos": len(loader.dataset),
    }

## 8. Train

In [ ]:
optimizer = torch.optim.AdamW(model.parameters(), lr=LEARNING_RATE, weight_decay=WEIGHT_DECAY)

history = []
best_metric = -1.0
best_path = CKPT_DIR / "best_model.pt"

for epoch in range(1, NUM_EPOCHS + 1):
    model.train()
    start = time.time()

    train_losses = []
    train_accs = []

    pbar = tqdm(train_loader, desc=f"epoch {epoch}/{NUM_EPOCHS}", leave=False)
    for video_ids, x, y, mask in pbar:
        x = x.to(device)
        y = y.to(device)
        mask = mask.to(device)

        optimizer.zero_grad(set_to_none=True)

        outputs = model(x)
        loss = mstcn_loss(outputs, y)

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=5.0)
        optimizer.step()

        acc = frame_accuracy_from_logits(outputs[-1], y, mask)
        train_losses.append(float(loss.item()))
        train_accs.append(acc)

        pbar.set_postfix(loss=np.mean(train_losses), acc=100*np.mean(train_accs))

    train_metrics = evaluate_model(model, train_loader, save_predictions=False)
    test_metrics = evaluate_model(model, test_loader, save_predictions=False)

    row = {
        "epoch": epoch,
        "loss": float(np.mean(train_losses)),
        "batch_train_acc": 100.0 * float(np.mean(train_accs)),
        "train_acc": train_metrics["acc"],
        "train_edit": train_metrics["edit"],
        "train_f1@10": train_metrics["f1@10"],
        "train_f1@25": train_metrics["f1@25"],
        "train_f1@50": train_metrics["f1@50"],
        "test_acc": test_metrics["acc"],
        "test_edit": test_metrics["edit"],
        "test_f1@10": test_metrics["f1@10"],
        "test_f1@25": test_metrics["f1@25"],
        "test_f1@50": test_metrics["f1@50"],
        "seconds": time.time() - start,
    }

    history.append(row)
    print(row)

    # Use segmental F1@25 as model-selection metric.
    select_metric = row["test_f1@25"]
    if select_metric > best_metric:
        best_metric = select_metric
        torch.save({
            "model_state": model.state_dict(),
            "config": {
                "feature_dim": feature_dim,
                "num_classes": num_classes,
                "num_stages": NUM_STAGES,
                "num_layers": NUM_LAYERS,
                "num_f_maps": NUM_F_MAPS,
                "dropout": DROPOUT,
                "split_id": SPLIT_ID,
                "data_root": str(DATA_ROOT),
            },
            "epoch": epoch,
            "metrics": row,
            "id_to_label": id_to_label,
            "label_to_id": label_to_id,
        }, best_path)
        print("saved best:", best_path)

df_history = pd.DataFrame(history)
history_path = OUT_ROOT / "training_history.csv"
df_history.to_csv(history_path, index=False)

print("history saved:", history_path)
display(df_history.tail())

epoch 1/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 1, 'loss': 10.907141913538394, 'batch_train_acc': 9.274796195652174, 'train_acc': 11.429794520547945, 'train_edit': 14.089720726013184, 'train_f1@10': 12.535061969993478, 'train_f1@25': 4.554848880191346, 'train_f1@50': 0.6283974777125463, 'test_acc': 11.681547619047619, 'test_edit': 14.356575965881348, 'test_f1@10': 12.713529856387, 'test_f1@25': 3.8624338624338628, 'test_f1@50': 0.1322751322751323, 'seconds': 30.319361925125122}
saved best: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/checkpoints/best_model.pt

epoch 2/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 2, 'loss': 9.896815859753152, 'batch_train_acc': 13.533457880434781, 'train_acc': 16.65667808219178, 'train_edit': 24.34276580810547, 'train_f1@10': 28.004065949271432, 'train_f1@25': 24.932933884988678, 'train_f1@50': 11.402675710894888, 'test_acc': 17.73313492063492, 'test_edit': 26.300704956054688, 'test_f1@10': 30.281383079002126, 'test_f1@25': 28.166784714403764, 'test_f1@50': 13.006768363911222, 'seconds': 25.4072527885437}
saved best: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/checkpoints/best_model.pt

epoch 3/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 3, 'loss': 9.433445764624555, 'batch_train_acc': 15.757472826086955, 'train_acc': 16.99486301369863, 'train_edit': 24.378314971923828, 'train_f1@10': 28.220382737506025, 'train_f1@25': 26.283355913492898, 'train_f1@50': 16.191984195408853, 'test_acc': 19.047619047619047, 'test_edit': 26.234569549560547, 'test_f1@10': 30.581092188235043, 'test_f1@25': 29.476194000003524, 'test_f1@50': 19.229013931394885, 'seconds': 25.63668465614319}
saved best: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/checkpoints/best_model.pt

epoch 4/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 4, 'loss': 9.051651581473973, 'batch_train_acc': 16.225373641304348, 'train_acc': 17.097602739726028, 'train_edit': 23.46412467956543, 'train_f1@10': 27.379479158588747, 'train_f1@25': 25.576430228827487, 'train_f1@50': 20.115798394907983, 'test_acc': 19.02281746031746, 'test_edit': 25.885770797729492, 'test_f1@10': 29.30877543972782, 'test_f1@25': 28.311901942854323, 'test_f1@50': 23.213759344711722, 'seconds': 25.57724404335022}

epoch 5/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 5, 'loss': 8.80697602811067, 'batch_train_acc': 16.30859375, 'train_acc': 17.363013698630137, 'train_edit': 24.054874420166016, 'train_f1@10': 27.9651433041844, 'train_f1@25': 26.165745213690418, 'train_f1@50': 14.257275829193638, 'test_acc': 19.072420634920636, 'test_edit': 25.89065170288086, 'test_f1@10': 30.195996684091924, 'test_f1@25': 29.543038531133767, 'test_f1@50': 18.187174377650567, 'seconds': 25.503321170806885}
saved best: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/checkpoints/best_model.pt

epoch 6/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 6, 'loss': 8.586101200269615, 'batch_train_acc': 16.421535326086957, 'train_acc': 17.45719178082192, 'train_edit': 24.373748779296875, 'train_f1@10': 28.247018962772383, 'train_f1@25': 26.467200227474198, 'train_f1@50': 12.121514710555807, 'test_acc': 18.92361111111111, 'test_edit': 26.22134017944336, 'test_f1@10': 30.572273846083373, 'test_f1@25': 29.979440753250277, 'test_f1@50': 15.143355321926752, 'seconds': 25.27198338508606}
saved best: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/checkpoints/best_model.pt

epoch 7/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 7, 'loss': 8.325596187425697, 'batch_train_acc': 16.841032608695652, 'train_acc': 17.803938356164384, 'train_edit': 27.41087532043457, 'train_f1@10': 29.91396617081549, 'train_f1@25': 28.605775503035776, 'train_f1@50': 21.084586646230484, 'test_acc': 19.717261904761905, 'test_edit': 29.712459564208984, 'test_f1@10': 32.55677303296351, 'test_f1@25': 31.811222287412765, 'test_f1@50': 25.358162560543512, 'seconds': 25.12681794166565}
saved best: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/checkpoints/best_model.pt

epoch 8/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 8, 'loss': 8.120671863141267, 'batch_train_acc': 19.436990489130434, 'train_acc': 22.705479452054796, 'train_edit': 29.76494789123535, 'train_f1@10': 33.91317011844812, 'train_f1@25': 31.186251019550777, 'train_f1@50': 24.196300207984333, 'test_acc': 23.46230158730159, 'test_edit': 32.14033889770508, 'test_f1@10': 34.92070176944126, 'test_f1@25': 32.64414785598259, 'test_f1@50': 26.66909978184488, 'seconds': 25.56075668334961}
saved best: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/checkpoints/best_model.pt

epoch 9/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 9, 'loss': 7.9064243150793985, 'batch_train_acc': 21.860563858695652, 'train_acc': 24.34931506849315, 'train_edit': 31.080291748046875, 'train_f1@10': 34.405421996233734, 'train_f1@25': 31.550327598734018, 'train_f1@50': 21.802882613778962, 'test_acc': 25.768849206349206, 'test_edit': 34.544437408447266, 'test_f1@10': 37.08281506075624, 'test_f1@25': 33.991644443325114, 'test_f1@50': 26.310493700199583, 'seconds': 25.547131061553955}
saved best: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/checkpoints/best_model.pt

epoch 10/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 10, 'loss': 7.7256807762643565, 'batch_train_acc': 23.11905570652174, 'train_acc': 26.502568493150687, 'train_edit': 27.80699348449707, 'train_f1@10': 33.79005259458205, 'train_f1@25': 29.9541685283394, 'train_f1@50': 19.01456280241428, 'test_acc': 27.901785714285715, 'test_edit': 28.775352478027344, 'test_f1@10': 35.01362102727649, 'test_f1@25': 31.113466300791227, 'test_f1@50': 20.267931894332452, 'seconds': 25.593281507492065}

epoch 11/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 11, 'loss': 7.617564678192139, 'batch_train_acc': 25.070482336956523, 'train_acc': 27.49571917808219, 'train_edit': 32.1057014465332, 'train_f1@10': 36.90081175733663, 'train_f1@25': 35.31916194059415, 'train_f1@50': 24.34146963405519, 'test_acc': 30.33234126984127, 'test_edit': 34.17202377319336, 'test_f1@10': 38.79322481388308, 'test_f1@25': 37.507486742430714, 'test_f1@50': 27.35931603928803, 'seconds': 24.767646312713623}
saved best: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/checkpoints/best_model.pt

epoch 12/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 12, 'loss': 7.492735427358876, 'batch_train_acc': 26.17272418478261, 'train_acc': 27.131849315068493, 'train_edit': 28.057783126831055, 'train_f1@10': 33.974942105079094, 'train_f1@25': 32.005325724503805, 'train_f1@50': 20.940973410151493, 'test_acc': 29.41468253968254, 'test_edit': 30.211483001708984, 'test_f1@10': 36.1854741248999, 'test_f1@25': 34.176982175931755, 'test_f1@50': 22.848936000196506, 'seconds': 25.118170022964478}

epoch 13/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 13, 'loss': 7.461347559224004, 'batch_train_acc': 25.97741168478261, 'train_acc': 27.85958904109589, 'train_edit': 30.77769660949707, 'train_f1@10': 35.778902898469035, 'train_f1@25': 33.05708071786468, 'train_f1@50': 22.262804791845465, 'test_acc': 28.67063492063492, 'test_edit': 32.28331756591797, 'test_f1@10': 36.00004529681664, 'test_f1@25': 33.20403049099791, 'test_f1@50': 22.660857238109195, 'seconds': 25.171926259994507}

epoch 14/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 14, 'loss': 7.307353092276531, 'batch_train_acc': 27.292798913043477, 'train_acc': 29.965753424657535, 'train_edit': 32.01019287109375, 'train_f1@10': 37.47929316855586, 'train_f1@25': 35.74514869811002, 'train_f1@50': 24.03546272422179, 'test_acc': 31.547619047619047, 'test_edit': 33.83502960205078, 'test_f1@10': 39.028765546622694, 'test_f1@25': 37.10009897509897, 'test_f1@50': 25.312950937950944, 'seconds': 25.572388172149658}

epoch 15/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 15, 'loss': 7.292010867077371, 'batch_train_acc': 27.68087635869565, 'train_acc': 29.95719178082192, 'train_edit': 33.184417724609375, 'train_f1@10': 38.41921093724075, 'train_f1@25': 35.920905779689015, 'train_f1@50': 25.960054360537843, 'test_acc': 33.08531746031746, 'test_edit': 35.117000579833984, 'test_f1@10': 39.92484574767487, 'test_f1@25': 37.53209409897085, 'test_f1@50': 27.715023396045805, 'seconds': 25.477551698684692}
saved best: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/checkpoints/best_model.pt

epoch 16/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 16, 'loss': 7.161313751469487, 'batch_train_acc': 28.603091032608695, 'train_acc': 30.67208904109589, 'train_edit': 35.16106414794922, 'train_f1@10': 40.31649322563908, 'train_f1@25': 38.83789115799591, 'train_f1@50': 28.383131004101994, 'test_acc': 31.919642857142858, 'test_edit': 36.81563186645508, 'test_f1@10': 40.905532505672554, 'test_f1@25': 39.30015595981982, 'test_f1@50': 28.546011191319316, 'seconds': 24.74090313911438}
saved best: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/checkpoints/best_model.pt

epoch 17/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 17, 'loss': 7.089599059975666, 'batch_train_acc': 29.976222826086957, 'train_acc': 32.12328767123287, 'train_edit': 34.56168746948242, 'train_f1@10': 41.47135915387326, 'train_f1@25': 39.238555528543436, 'train_f1@50': 27.774317566219263, 'test_acc': 31.498015873015873, 'test_edit': 34.265159606933594, 'test_f1@10': 40.5474411987017, 'test_f1@25': 38.44703719353579, 'test_f1@50': 27.414222682079824, 'seconds': 24.387781381607056}

epoch 18/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 18, 'loss': 7.037291703016861, 'batch_train_acc': 31.031759510869566, 'train_acc': 33.87842465753425, 'train_edit': 35.26448440551758, 'train_f1@10': 41.91824460569424, 'train_f1@25': 38.5540270120246, 'train_f1@50': 25.214624483762275, 'test_acc': 35.68948412698413, 'test_edit': 36.871219635009766, 'test_f1@10': 42.66205057521584, 'test_f1@25': 39.37305341717106, 'test_f1@50': 26.717012368272872, 'seconds': 24.213241815567017}
saved best: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/checkpoints/best_model.pt

epoch 19/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 19, 'loss': 7.0253690533016036, 'batch_train_acc': 30.78040081521739, 'train_acc': 34.101027397260275, 'train_edit': 35.81941604614258, 'train_f1@10': 42.76837910500279, 'train_f1@25': 38.68279288756727, 'train_f1@50': 26.728302116900018, 'test_acc': 33.95337301587302, 'test_edit': 35.22092819213867, 'test_f1@10': 42.10815341417582, 'test_f1@25': 37.1191917585475, 'test_f1@50': 24.734641784711812, 'seconds': 24.33903479576111}

epoch 20/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 20, 'loss': 6.925988653431768, 'batch_train_acc': 32.193444293478265, 'train_acc': 36.044520547945204, 'train_edit': 37.66750717163086, 'train_f1@10': 45.26912534819465, 'train_f1@25': 42.814145910942855, 'train_f1@50': 30.147057370063017, 'test_acc': 35.09424603174603, 'test_edit': 37.299224853515625, 'test_f1@10': 44.74747163822794, 'test_f1@25': 42.488629290099865, 'test_f1@50': 29.18308938441992, 'seconds': 24.101325273513794}
saved best: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/checkpoints/best_model.pt

epoch 21/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 21, 'loss': 6.8406552957451865, 'batch_train_acc': 33.42306385869565, 'train_acc': 36.00599315068493, 'train_edit': 38.175472259521484, 'train_f1@10': 45.016382601193236, 'train_f1@25': 41.41799653252111, 'train_f1@50': 29.72334119010187, 'test_acc': 35.66468253968254, 'test_edit': 37.9817008972168, 'test_f1@10': 44.073447496066535, 'test_f1@25': 40.516503998646854, 'test_f1@50': 29.33988079821413, 'seconds': 25.258715867996216}

epoch 22/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 22, 'loss': 6.756390872208969, 'batch_train_acc': 33.99966032608695, 'train_acc': 37.12756849315068, 'train_edit': 39.10526657104492, 'train_f1@10': 46.271056996214966, 'train_f1@25': 44.06117536338814, 'train_f1@50': 31.03902117598627, 'test_acc': 36.879960317460316, 'test_edit': 38.54812240600586, 'test_f1@10': 46.100434281456685, 'test_f1@25': 44.00559129375656, 'test_f1@50': 30.02811121858741, 'seconds': 25.894832611083984}
saved best: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/checkpoints/best_model.pt

epoch 23/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 23, 'loss': 6.7809712679489795, 'batch_train_acc': 33.79670516304348, 'train_acc': 38.67294520547945, 'train_edit': 40.5205078125, 'train_f1@10': 48.21434090658295, 'train_f1@25': 44.93226316320488, 'train_f1@50': 31.91525111043538, 'test_acc': 37.99603174603175, 'test_edit': 39.508548736572266, 'test_f1@10': 47.158071205690256, 'test_f1@25': 44.55568901997473, 'test_f1@50': 30.92245717245717, 'seconds': 25.68584418296814}
saved best: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/checkpoints/best_model.pt

epoch 24/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 24, 'loss': 6.622057272040325, 'batch_train_acc': 36.05638586956522, 'train_acc': 38.326198630136986, 'train_edit': 39.956539154052734, 'train_f1@10': 46.81272342573713, 'train_f1@25': 44.571046533375295, 'train_f1@50': 31.431003167304542, 'test_acc': 38.51686507936508, 'test_edit': 41.10795974731445, 'test_f1@10': 46.69115056019818, 'test_f1@25': 44.12324888515366, 'test_f1@50': 31.272583236868954, 'seconds': 25.22441029548645}

epoch 25/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 25, 'loss': 6.607793745787247, 'batch_train_acc': 36.40455163043478, 'train_acc': 40.38955479452055, 'train_edit': 42.84490966796875, 'train_f1@10': 49.59664315002752, 'train_f1@25': 46.8495536158711, 'train_f1@50': 35.38703580867159, 'test_acc': 39.55853174603175, 'test_edit': 42.48881912231445, 'test_f1@10': 48.81505839839173, 'test_f1@25': 46.16342872295254, 'test_f1@50': 34.84988996893759, 'seconds': 24.403470039367676}
saved best: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/checkpoints/best_model.pt

epoch 26/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 26, 'loss': 6.545738261678944, 'batch_train_acc': 36.925101902173914, 'train_acc': 40.1583904109589, 'train_edit': 42.30226516723633, 'train_f1@10': 48.834345124836666, 'train_f1@25': 46.77772189758492, 'train_f1@50': 33.85398885741352, 'test_acc': 40.99702380952381, 'test_edit': 43.352230072021484, 'test_f1@10': 48.92787107072821, 'test_f1@25': 46.87783556831175, 'test_f1@50': 33.78250937774747, 'seconds': 25.182310104370117}
saved best: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/checkpoints/best_model.pt

epoch 27/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 27, 'loss': 6.4882947258327315, 'batch_train_acc': 37.309782608695656, 'train_acc': 39.417808219178085, 'train_edit': 41.74223709106445, 'train_f1@10': 48.505145763002325, 'train_f1@25': 46.60544527546945, 'train_f1@50': 34.16199721578448, 'test_acc': 39.285714285714285, 'test_edit': 41.5789680480957, 'test_f1@10': 47.77740700009607, 'test_f1@25': 45.85976335626195, 'test_f1@50': 33.59138579026534, 'seconds': 24.712291955947876}

epoch 28/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 28, 'loss': 6.443342633869337, 'batch_train_acc': 37.96959918478261, 'train_acc': 41.15582191780822, 'train_edit': 43.02179718017578, 'train_f1@10': 50.58445570008825, 'train_f1@25': 47.32740770734324, 'train_f1@50': 33.97389745405459, 'test_acc': 40.97222222222222, 'test_edit': 42.710853576660156, 'test_f1@10': 50.36398300578973, 'test_f1@25': 47.521526740714414, 'test_f1@50': 33.162719115100074, 'seconds': 25.628310203552246}
saved best: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/checkpoints/best_model.pt

epoch 29/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 29, 'loss': 6.465275297994199, 'batch_train_acc': 37.61973505434783, 'train_acc': 41.429794520547944, 'train_edit': 43.938682556152344, 'train_f1@10': 50.67018560944831, 'train_f1@25': 48.62552536102093, 'train_f1@50': 35.01429034748938, 'test_acc': 39.50892857142857, 'test_edit': 42.960758209228516, 'test_f1@10': 48.870311786978455, 'test_f1@25': 46.32044762997144, 'test_f1@50': 33.47800127562032, 'seconds': 24.754950761795044}

epoch 30/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 30, 'loss': 6.421401220819225, 'batch_train_acc': 37.88722826086957, 'train_acc': 39.169520547945204, 'train_edit': 41.76136016845703, 'train_f1@10': 48.29741025158028, 'train_f1@25': 46.00184622656419, 'train_f1@50': 33.90805867961387, 'test_acc': 40.451388888888886, 'test_edit': 42.38992691040039, 'test_f1@10': 48.36670513841382, 'test_f1@25': 46.24792082074995, 'test_f1@50': 34.91823199106112, 'seconds': 24.76303768157959}

epoch 31/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 31, 'loss': 6.586721399556035, 'batch_train_acc': 37.064368206521735, 'train_acc': 43.476027397260275, 'train_edit': 45.96762466430664, 'train_f1@10': 52.53502311771853, 'train_f1@25': 50.3595574114309, 'train_f1@50': 36.882154867247536, 'test_acc': 42.08829365079365, 'test_edit': 44.94803237915039, 'test_f1@10': 50.78419596276739, 'test_f1@25': 49.32784367308176, 'test_f1@50': 34.405431429240956, 'seconds': 24.50557565689087}
saved best: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/checkpoints/best_model.pt

epoch 32/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 32, 'loss': 6.2076448357623555, 'batch_train_acc': 39.8046875, 'train_acc': 41.85787671232877, 'train_edit': 44.69667053222656, 'train_f1@10': 51.34888570333776, 'train_f1@25': 49.020298765161776, 'train_f1@50': 34.99089057821935, 'test_acc': 39.50892857142857, 'test_edit': 43.62843322753906, 'test_f1@10': 48.93019238257334, 'test_f1@25': 47.06422765946575, 'test_f1@50': 31.66364499697833, 'seconds': 24.792208433151245}

epoch 33/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 33, 'loss': 6.197931372601053, 'batch_train_acc': 39.99320652173913, 'train_acc': 43.98544520547945, 'train_edit': 46.36513137817383, 'train_f1@10': 52.86887566279185, 'train_f1@25': 50.65605233695483, 'train_f1@50': 37.999162937519095, 'test_acc': 42.68353174603175, 'test_edit': 45.01920700073242, 'test_f1@10': 51.65987671940052, 'test_f1@25': 49.93109183585374, 'test_f1@50': 36.930366811319196, 'seconds': 24.234244108200073}
saved best: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/checkpoints/best_model.pt

epoch 34/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 34, 'loss': 6.189631430999093, 'batch_train_acc': 40.70142663043478, 'train_acc': 42.49143835616438, 'train_edit': 43.68735122680664, 'train_f1@10': 51.09026270085899, 'train_f1@25': 47.9182000625393, 'train_f1@50': 35.78661260621374, 'test_acc': 42.21230158730159, 'test_edit': 43.897865295410156, 'test_f1@10': 50.76961728747443, 'test_f1@25': 47.601429655001084, 'test_f1@50': 35.69760376307996, 'seconds': 24.4178409576416}

epoch 35/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 35, 'loss': 6.135438431864199, 'batch_train_acc': 41.33661684782609, 'train_acc': 43.97260273972603, 'train_edit': 45.40737533569336, 'train_f1@10': 53.121219645695874, 'train_f1@25': 50.063544444185055, 'train_f1@50': 37.223042100258056, 'test_acc': 42.55952380952381, 'test_edit': 42.843284606933594, 'test_f1@10': 50.774356816023484, 'test_f1@25': 48.658241009431485, 'test_f1@50': 35.59985869509679, 'seconds': 24.804224967956543}

epoch 36/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 36, 'loss': 6.1569113938704785, 'batch_train_acc': 40.45261548913043, 'train_acc': 42.542808219178085, 'train_edit': 45.22612380981445, 'train_f1@10': 51.755483705121094, 'train_f1@25': 49.81151025087367, 'train_f1@50': 36.691265199121766, 'test_acc': 42.26190476190476, 'test_edit': 45.42878723144531, 'test_f1@10': 51.74743246171818, 'test_f1@25': 49.67938807224522, 'test_f1@50': 37.366432068813026, 'seconds': 24.528013944625854}

epoch 37/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 37, 'loss': 6.116306978723277, 'batch_train_acc': 42.03549592391305, 'train_acc': 44.730308219178085, 'train_edit': 45.91438293457031, 'train_f1@10': 54.05688012184788, 'train_f1@25': 50.86857959168596, 'train_f1@50': 37.833872043884135, 'test_acc': 43.576388888888886, 'test_edit': 44.47704315185547, 'test_f1@10': 51.93093502617312, 'test_f1@25': 49.22506505839839, 'test_f1@50': 37.3544709258995, 'seconds': 24.549211502075195}

epoch 38/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 38, 'loss': 6.1078331263168995, 'batch_train_acc': 41.770550271739125, 'train_acc': 43.44178082191781, 'train_edit': 44.9713249206543, 'train_f1@10': 51.84452115616499, 'train_f1@25': 49.5901727648303, 'train_f1@50': 36.28623241294474, 'test_acc': 41.74107142857143, 'test_edit': 43.02720642089844, 'test_f1@10': 48.65955032621699, 'test_f1@25': 46.70144890382985, 'test_f1@50': 33.59707972803211, 'seconds': 25.093766927719116}

epoch 39/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 39, 'loss': 6.091921505720719, 'batch_train_acc': 41.64317255434782, 'train_acc': 42.87671232876713, 'train_edit': 45.64127731323242, 'train_f1@10': 52.194025152929264, 'train_f1@25': 50.17679428638333, 'train_f1@50': 37.648850008439055, 'test_acc': 42.46031746031746, 'test_edit': 45.29257583618164, 'test_f1@10': 51.046971106494915, 'test_f1@25': 49.23646239122429, 'test_f1@50': 37.23080050461003, 'seconds': 24.655401706695557}

epoch 40/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 40, 'loss': 6.082701019618822, 'batch_train_acc': 42.30383831521739, 'train_acc': 43.788527397260275, 'train_edit': 45.28076934814453, 'train_f1@10': 53.11546062049688, 'train_f1@25': 50.01538008951386, 'train_f1@50': 35.87345631805745, 'test_acc': 42.93154761904762, 'test_edit': 44.658607482910156, 'test_f1@10': 52.02181856943761, 'test_f1@25': 49.446715101477004, 'test_f1@50': 34.06372397443826, 'seconds': 25.09735631942749}

epoch 41/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 41, 'loss': 6.040769317875737, 'batch_train_acc': 42.10767663043479, 'train_acc': 45.01284246575342, 'train_edit': 46.21390151977539, 'train_f1@10': 53.51003790729817, 'train_f1@25': 51.22361466539548, 'train_f1@50': 38.32339388161306, 'test_acc': 44.22123015873016, 'test_edit': 45.73884582519531, 'test_f1@10': 51.60172279219898, 'test_f1@25': 49.752275942752135, 'test_f1@50': 37.10965841918223, 'seconds': 24.667345762252808}

epoch 42/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 42, 'loss': 6.038273375967274, 'batch_train_acc': 43.05961277173913, 'train_acc': 44.92722602739726, 'train_edit': 45.768836975097656, 'train_f1@10': 53.62065799273696, 'train_f1@25': 50.95153539271187, 'train_f1@50': 37.061322239404426, 'test_acc': 42.73313492063492, 'test_edit': 43.0065803527832, 'test_f1@10': 50.371223793842844, 'test_f1@25': 47.68186068781307, 'test_f1@50': 35.15744066339304, 'seconds': 24.090042114257812}

epoch 43/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 43, 'loss': 6.011212141617484, 'batch_train_acc': 42.86769701086957, 'train_acc': 44.61900684931507, 'train_edit': 47.087623596191406, 'train_f1@10': 53.666719617565704, 'train_f1@25': 51.76171455905541, 'train_f1@50': 39.8386874339735, 'test_acc': 42.88194444444444, 'test_edit': 44.210914611816406, 'test_f1@10': 50.68475836332979, 'test_f1@25': 49.28851131232083, 'test_f1@50': 37.47467479610337, 'seconds': 24.777995347976685}

epoch 44/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 44, 'loss': 6.012580964876258, 'batch_train_acc': 43.01120923913043, 'train_acc': 45.625, 'train_edit': 48.26739501953125, 'train_f1@10': 54.593923580224946, 'train_f1@25': 51.54405792077025, 'train_f1@50': 39.06903218547054, 'test_acc': 42.410714285714285, 'test_edit': 45.54264450073242, 'test_f1@10': 51.53626796483939, 'test_f1@25': 47.96675766913862, 'test_f1@50': 35.84066726923869, 'seconds': 24.279669523239136}

epoch 45/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 45, 'loss': 5.970099936360898, 'batch_train_acc': 43.193783967391305, 'train_acc': 46.03595890410959, 'train_edit': 46.48488235473633, 'train_f1@10': 54.30512295923254, 'train_f1@25': 51.96582394013901, 'train_f1@50': 38.18263186585105, 'test_acc': 43.20436507936508, 'test_edit': 43.5213508605957, 'test_f1@10': 50.031740746026465, 'test_f1@25': 48.579931972789105, 'test_f1@50': 34.88487262296786, 'seconds': 24.371593713760376}

epoch 46/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 46, 'loss': 5.913403137870457, 'batch_train_acc': 44.30027173913044, 'train_acc': 44.404965753424655, 'train_edit': 46.4676513671875, 'train_f1@10': 52.84403305978648, 'train_f1@25': 50.67417247896701, 'train_f1@50': 38.51023177735506, 'test_acc': 43.50198412698413, 'test_edit': 45.15101623535156, 'test_f1@10': 50.8568702021083, 'test_f1@25': 49.01323544180688, 'test_f1@50': 36.731711850759474, 'seconds': 23.8482928276062}

epoch 47/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 47, 'loss': 5.894352145816969, 'batch_train_acc': 43.90285326086957, 'train_acc': 45.71489726027397, 'train_edit': 47.240352630615234, 'train_f1@10': 54.30206646473769, 'train_f1@25': 52.19487742090482, 'train_f1@50': 39.33852581969021, 'test_acc': 44.04761904761905, 'test_edit': 46.63170623779297, 'test_f1@10': 52.85659776731205, 'test_f1@25': 50.249485963771676, 'test_f1@50': 38.376924001924, 'seconds': 24.322142124176025}
saved best: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/checkpoints/best_model.pt

epoch 48/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 48, 'loss': 5.934368527453879, 'batch_train_acc': 44.51171875, 'train_acc': 47.24743150684932, 'train_edit': 49.26980972290039, 'train_f1@10': 56.13420787735856, 'train_f1@25': 54.13737936340676, 'train_f1@50': 41.731183200361286, 'test_acc': 45.61011904761905, 'test_edit': 47.939659118652344, 'test_f1@10': 54.14578807435951, 'test_f1@25': 52.26921887636173, 'test_f1@50': 39.533246735627685, 'seconds': 24.830613374710083}
saved best: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/checkpoints/best_model.pt

epoch 49/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 49, 'loss': 5.927011272181636, 'batch_train_acc': 44.56351902173913, 'train_acc': 47.45291095890411, 'train_edit': 49.02812957763672, 'train_f1@10': 55.66859244256504, 'train_f1@25': 53.75147037133338, 'train_f1@50': 40.192994220391476, 'test_acc': 44.49404761904762, 'test_edit': 47.00050354003906, 'test_f1@10': 52.52257883210264, 'test_f1@25': 49.81337445623159, 'test_f1@50': 36.19384143193667, 'seconds': 25.412935256958008}

epoch 50/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 50, 'loss': 5.927758942479673, 'batch_train_acc': 44.335088315217384, 'train_acc': 47.632705479452056, 'train_edit': 48.335914611816406, 'train_f1@10': 55.51621608984623, 'train_f1@25': 53.310081090903, 'train_f1@50': 41.02862016218181, 'test_acc': 45.75892857142857, 'test_edit': 46.79689407348633, 'test_f1@10': 53.33282238044143, 'test_f1@25': 51.025759954331384, 'test_f1@50': 39.08983983388745, 'seconds': 25.119906663894653}

epoch 51/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 51, 'loss': 5.913605036942855, 'batch_train_acc': 45.1078464673913, 'train_acc': 48.03082191780822, 'train_edit': 49.080692291259766, 'train_f1@10': 56.12295136146869, 'train_f1@25': 54.03822026303896, 'train_f1@50': 40.64053613590278, 'test_acc': 44.56845238095238, 'test_edit': 46.517704010009766, 'test_f1@10': 52.76634520682139, 'test_f1@25': 49.82001684382637, 'test_f1@50': 37.52222755198946, 'seconds': 24.756645679473877}

epoch 52/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 52, 'loss': 5.861848592758179, 'batch_train_acc': 44.57286005434782, 'train_acc': 46.24143835616438, 'train_edit': 46.233123779296875, 'train_f1@10': 53.81639764345243, 'train_f1@25': 51.658375680635956, 'train_f1@50': 38.827938613897516, 'test_acc': 43.75, 'test_edit': 43.9720344543457, 'test_f1@10': 50.61351787542264, 'test_f1@25': 48.115561686990254, 'test_f1@50': 36.86809883238455, 'seconds': 24.349547147750854}

epoch 53/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 53, 'loss': 5.888198261675627, 'batch_train_acc': 45.068783967391305, 'train_acc': 49.25085616438356, 'train_edit': 49.732845306396484, 'train_f1@10': 56.942538815826495, 'train_f1@25': 54.59283372639536, 'train_f1@50': 42.039853031291386, 'test_acc': 46.99900793650794, 'test_edit': 47.87871551513672, 'test_f1@10': 53.99899262994501, 'test_f1@25': 52.052544016829735, 'test_f1@50': 39.997178747178744, 'seconds': 24.812283277511597}

epoch 54/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 54, 'loss': 5.835064027620398, 'batch_train_acc': 44.89809782608695, 'train_acc': 47.73116438356164, 'train_edit': 49.771339416503906, 'train_f1@10': 56.55856532669587, 'train_f1@25': 54.77209380734764, 'train_f1@50': 42.59000320120384, 'test_acc': 45.982142857142854, 'test_edit': 48.14358139038086, 'test_f1@10': 54.96268281982567, 'test_f1@25': 53.514069704545896, 'test_f1@50': 40.3952815262339, 'seconds': 24.71786642074585}
saved best: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/checkpoints/best_model.pt

epoch 55/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 55, 'loss': 5.816002918326336, 'batch_train_acc': 46.02072010869565, 'train_acc': 48.06078767123287, 'train_edit': 49.59613037109375, 'train_f1@10': 56.93791822377641, 'train_f1@25': 54.38952920792163, 'train_f1@50': 41.340584621305815, 'test_acc': 45.58531746031746, 'test_edit': 47.65494918823242, 'test_f1@10': 54.85094821404345, 'test_f1@25': 50.80192404597166, 'test_f1@50': 39.72729100705291, 'seconds': 24.196288347244263}

epoch 56/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 56, 'loss': 5.803237355273703, 'batch_train_acc': 46.334069293478265, 'train_acc': 47.919520547945204, 'train_edit': 49.200748443603516, 'train_f1@10': 56.25236863593028, 'train_f1@25': 53.87740645959824, 'train_f1@50': 40.64183723430299, 'test_acc': 44.642857142857146, 'test_edit': 46.50163650512695, 'test_f1@10': 52.767098421860325, 'test_f1@25': 51.36423761423762, 'test_f1@50': 36.848165062450775, 'seconds': 23.967347145080566}

epoch 57/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 57, 'loss': 5.851195470146511, 'batch_train_acc': 45.834748641304344, 'train_acc': 49.884417808219176, 'train_edit': 51.98026657104492, 'train_f1@10': 59.20211770725469, 'train_f1@25': 56.241001958467706, 'train_f1@50': 42.838664189691585, 'test_acc': 46.676587301587304, 'test_edit': 49.97370147705078, 'test_f1@10': 56.652670521718136, 'test_f1@25': 53.97142980476313, 'test_f1@50': 40.879332307903745, 'seconds': 24.403448820114136}
saved best: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/checkpoints/best_model.pt

epoch 58/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 58, 'loss': 5.779230719027312, 'batch_train_acc': 46.55995244565217, 'train_acc': 48.6986301369863, 'train_edit': 49.71129608154297, 'train_f1@10': 56.98350965222439, 'train_f1@25': 54.613011809123805, 'train_f1@50': 42.113747509094004, 'test_acc': 46.354166666666664, 'test_edit': 46.5410041809082, 'test_f1@10': 53.251891406653314, 'test_f1@25': 51.737446856494465, 'test_f1@50': 39.31178169273407, 'seconds': 24.530633449554443}

epoch 59/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 59, 'loss': 5.877790212631226, 'batch_train_acc': 45.98930027173913, 'train_acc': 45.826198630136986, 'train_edit': 47.621002197265625, 'train_f1@10': 54.12227756798667, 'train_f1@25': 51.60662123041253, 'train_f1@50': 39.0437890853886, 'test_acc': 43.99801587301587, 'test_edit': 46.61170959472656, 'test_f1@10': 51.438528402814114, 'test_f1@25': 49.134613182232236, 'test_f1@50': 36.776552371790466, 'seconds': 25.139228343963623}

epoch 60/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 60, 'loss': 5.820359572120335, 'batch_train_acc': 46.38671875, 'train_acc': 48.300513698630134, 'train_edit': 50.47874450683594, 'train_f1@10': 56.93287876507055, 'train_f1@25': 54.68607952169596, 'train_f1@50': 40.753528435035285, 'test_acc': 44.89087301587302, 'test_edit': 46.78130340576172, 'test_f1@10': 52.64020591401544, 'test_f1@25': 50.99670171098742, 'test_f1@50': 36.07432030051078, 'seconds': 25.640544891357422}

epoch 61/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 61, 'loss': 5.79649571750475, 'batch_train_acc': 47.31317934782609, 'train_acc': 48.300513698630134, 'train_edit': 49.500328063964844, 'train_f1@10': 56.442733066020736, 'train_f1@25': 54.18843751377998, 'train_f1@50': 41.358045683388156, 'test_acc': 45.21329365079365, 'test_edit': 47.76502227783203, 'test_f1@10': 54.079593246259904, 'test_f1@25': 50.78851043136758, 'test_f1@50': 37.75014667871811, 'seconds': 25.08087420463562}

epoch 62/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 62, 'loss': 5.835073502167411, 'batch_train_acc': 46.196501358695656, 'train_acc': 50.25256849315068, 'train_edit': 50.82819366455078, 'train_f1@10': 57.694267110363, 'train_f1@25': 55.74947598064037, 'train_f1@50': 43.604824019207584, 'test_acc': 46.99900793650794, 'test_edit': 47.90517044067383, 'test_f1@10': 54.48183430326287, 'test_f1@25': 52.19819862677005, 'test_f1@50': 41.054827007207955, 'seconds': 24.89876389503479}

epoch 63/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 63, 'loss': 5.688394619070965, 'batch_train_acc': 47.55095108695652, 'train_acc': 51.070205479452056, 'train_edit': 50.585697174072266, 'train_f1@10': 58.270211523636185, 'train_f1@25': 55.85043894461703, 'train_f1@50': 43.21237476374463, 'test_acc': 45.65972222222222, 'test_edit': 46.92255783081055, 'test_f1@10': 53.450044223853745, 'test_f1@25': 50.219163552496894, 'test_f1@50': 38.7638662043424, 'seconds': 24.91250991821289}

epoch 64/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 64, 'loss': 5.827744898588761, 'batch_train_acc': 46.88858695652174, 'train_acc': 50.06421232876713, 'train_edit': 50.91017150878906, 'train_f1@10': 58.258158128021144, 'train_f1@25': 55.547677968910854, 'train_f1@50': 43.62914254695077, 'test_acc': 46.89980158730159, 'test_edit': 48.117286682128906, 'test_f1@10': 54.676381819238955, 'test_f1@25': 52.09398185588662, 'test_f1@50': 41.21634097824573, 'seconds': 24.996593952178955}

epoch 65/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 65, 'loss': 5.8319273720616875, 'batch_train_acc': 47.59765625, 'train_acc': 49.90582191780822, 'train_edit': 49.11021041870117, 'train_f1@10': 56.154798017811714, 'train_f1@25': 53.61123731671677, 'train_f1@50': 42.11225285369121, 'test_acc': 44.17162698412698, 'test_edit': 44.436256408691406, 'test_f1@10': 50.29956815671101, 'test_f1@25': 47.43349243349243, 'test_f1@50': 37.15172613982138, 'seconds': 25.37017059326172}

epoch 66/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 66, 'loss': 5.698679737422777, 'batch_train_acc': 48.46297554347826, 'train_acc': 50.04708904109589, 'train_edit': 50.35974884033203, 'train_f1@10': 56.9727988906071, 'train_f1@25': 54.914976956072856, 'train_f1@50': 42.69865370550302, 'test_acc': 45.833333333333336, 'test_edit': 46.49266052246094, 'test_f1@10': 52.192932728647015, 'test_f1@25': 49.765998992189466, 'test_f1@50': 38.2683916612488, 'seconds': 25.05421805381775}

epoch 67/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 67, 'loss': 5.757326623667842, 'batch_train_acc': 48.91813858695652, 'train_acc': 48.570205479452056, 'train_edit': 48.9809455871582, 'train_f1@10': 55.73925712795576, 'train_f1@25': 53.57636883664281, 'train_f1@50': 40.44395463744779, 'test_acc': 44.76686507936508, 'test_edit': 44.86300277709961, 'test_f1@10': 50.93794433080148, 'test_f1@25': 48.542132470703905, 'test_f1@50': 36.410606589178016, 'seconds': 25.137572288513184}

epoch 68/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 68, 'loss': 5.752098145692245, 'batch_train_acc': 48.5444972826087, 'train_acc': 52.41438356164384, 'train_edit': 52.30248260498047, 'train_f1@10': 59.212613490010746, 'train_f1@25': 57.3433339871696, 'train_f1@50': 45.6468900201777, 'test_acc': 48.288690476190474, 'test_edit': 49.40869903564453, 'test_f1@10': 55.64802701707463, 'test_f1@25': 52.94020573782478, 'test_f1@50': 41.35878671592957, 'seconds': 25.764203786849976}

epoch 69/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 69, 'loss': 5.675722194754559, 'batch_train_acc': 47.90675951086957, 'train_acc': 51.81506849315068, 'train_edit': 52.22306442260742, 'train_f1@10': 59.32404999870753, 'train_f1@25': 57.35229021359159, 'train_f1@50': 44.95058670401136, 'test_acc': 48.90873015873016, 'test_edit': 49.14902877807617, 'test_f1@10': 55.45678527821384, 'test_f1@25': 54.384011050677714, 'test_f1@50': 42.61379933998981, 'seconds': 25.453256845474243}
saved best: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/checkpoints/best_model.pt

epoch 70/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 70, 'loss': 5.637203931808472, 'batch_train_acc': 49.30961277173913, 'train_acc': 51.32277397260274, 'train_edit': 51.00579071044922, 'train_f1@10': 58.48816328268383, 'train_f1@25': 55.85325557243366, 'train_f1@50': 44.18551102626445, 'test_acc': 46.354166666666664, 'test_edit': 47.34489440917969, 'test_f1@10': 53.58341724413153, 'test_f1@25': 50.18809783690736, 'test_f1@50': 40.286980435789964, 'seconds': 25.710733652114868}

epoch 71/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 71, 'loss': 5.654863119125366, 'batch_train_acc': 49.361413043478265, 'train_acc': 50.32534246575342, 'train_edit': 51.11567687988281, 'train_f1@10': 58.15669300258341, 'train_f1@25': 55.73660433934406, 'train_f1@50': 43.55297442283744, 'test_acc': 44.12202380952381, 'test_edit': 46.76807403564453, 'test_f1@10': 51.842980652504465, 'test_f1@25': 49.50758016234206, 'test_f1@50': 38.7473615449806, 'seconds': 25.482218503952026}

epoch 72/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 72, 'loss': 5.689193248748779, 'batch_train_acc': 48.741508152173914, 'train_acc': 51.31849315068493, 'train_edit': 51.93316650390625, 'train_f1@10': 58.67785030798729, 'train_f1@25': 56.789368546217865, 'train_f1@50': 44.46344941207955, 'test_acc': 47.66865079365079, 'test_edit': 49.0791130065918, 'test_f1@10': 54.74667308000642, 'test_f1@25': 53.37942921276255, 'test_f1@50': 41.85240024525739, 'seconds': 25.261980772018433}

epoch 73/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 73, 'loss': 5.744245197461999, 'batch_train_acc': 48.47486413043478, 'train_acc': 52.51284246575342, 'train_edit': 51.97377395629883, 'train_f1@10': 59.41704590959224, 'train_f1@25': 57.591973721506356, 'train_f1@50': 45.37483241532396, 'test_acc': 47.470238095238095, 'test_edit': 47.050106048583984, 'test_f1@10': 54.00219709743519, 'test_f1@25': 52.306026204835725, 'test_f1@50': 39.82268062625206, 'seconds': 21.711849451065063}

epoch 74/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 74, 'loss': 5.673113149145375, 'batch_train_acc': 49.50492527173913, 'train_acc': 53.38184931506849, 'train_edit': 52.29897689819336, 'train_f1@10': 60.152301085520264, 'train_f1@25': 57.65579891949754, 'train_f1@50': 45.384217190724044, 'test_acc': 46.254960317460316, 'test_edit': 47.09592819213867, 'test_f1@10': 53.68405624358005, 'test_f1@25': 50.40547635785731, 'test_f1@50': 40.03353568829759, 'seconds': 25.71066665649414}

epoch 75/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 75, 'loss': 5.717278553091961, 'batch_train_acc': 48.70923913043478, 'train_acc': 50.85616438356164, 'train_edit': 50.06305694580078, 'train_f1@10': 57.98990241113528, 'train_f1@25': 55.167528818213746, 'train_f1@50': 41.98308692829241, 'test_acc': 45.982142857142854, 'test_edit': 44.7567024230957, 'test_f1@10': 51.54000540905302, 'test_f1@25': 48.94262263309882, 'test_f1@50': 36.94139634615826, 'seconds': 25.215662956237793}

epoch 76/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 76, 'loss': 5.6676981138146445, 'batch_train_acc': 50.309103260869556, 'train_acc': 50.509417808219176, 'train_edit': 50.73319625854492, 'train_f1@10': 58.117457314375116, 'train_f1@25': 55.64935159969406, 'train_f1@50': 43.81206008603269, 'test_acc': 47.395833333333336, 'test_edit': 48.52245330810547, 'test_f1@10': 55.50580592247258, 'test_f1@25': 52.660879684689206, 'test_f1@50': 42.03367399795972, 'seconds': 24.69122862815857}

epoch 77/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 77, 'loss': 5.567222481188566, 'batch_train_acc': 50.205502717391305, 'train_acc': 53.882705479452056, 'train_edit': 53.156883239746094, 'train_f1@10': 60.17407136242753, 'train_f1@25': 58.52632565303798, 'train_f1@50': 46.83996939133926, 'test_acc': 46.77579365079365, 'test_edit': 47.15325164794922, 'test_f1@10': 52.80659375897472, 'test_f1@25': 50.832086784467734, 'test_f1@50': 40.104773973821594, 'seconds': 24.510499000549316}

epoch 78/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 78, 'loss': 5.562506509863812, 'batch_train_acc': 50.55451766304348, 'train_acc': 53.03082191780822, 'train_edit': 52.41033172607422, 'train_f1@10': 58.81996124119412, 'train_f1@25': 56.98824235125605, 'train_f1@50': 45.11864201247763, 'test_acc': 45.36210317460318, 'test_edit': 46.68824005126953, 'test_f1@10': 50.282838854267425, 'test_f1@25': 48.42931759598426, 'test_f1@50': 39.02431122669218, 'seconds': 24.902006149291992}

epoch 79/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 79, 'loss': 5.685786464939946, 'batch_train_acc': 50.00764266304347, 'train_acc': 50.54366438356164, 'train_edit': 50.41645050048828, 'train_f1@10': 57.19892170234636, 'train_f1@25': 55.54910500458446, 'train_f1@50': 43.87617405425624, 'test_acc': 46.23015873015873, 'test_edit': 46.52887725830078, 'test_f1@10': 52.18674843674844, 'test_f1@25': 50.58828076685219, 'test_f1@50': 39.93596570977523, 'seconds': 24.332621335983276}

epoch 80/80:   0%|          | 0/46 [00:00<?, ?it/s]

{'epoch': 80, 'loss': 5.529996757921965, 'batch_train_acc': 51.20329483695652, 'train_acc': 51.25, 'train_edit': 51.689117431640625, 'train_f1@10': 58.597081571396636, 'train_f1@25': 56.658872520173894, 'train_f1@50': 45.13056806207491, 'test_acc': 47.048611111111114, 'test_edit': 47.50346374511719, 'test_f1@10': 53.00913372341943, 'test_f1@25': 51.535402428259566, 'test_f1@50': 40.28584730965683, 'seconds': 24.2597439289093}
history saved: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/training_history.csv

,epoch,loss,batch_train_acc,train_acc,train_edit,train_f1@10,train_f1@25,train_f1@50,test_acc,test_edit,test_f1@10,test_f1@25,test_f1@50,seconds
75,76,5.667698,50.309103,50.509418,50.733196,58.117457,55.649352,43.812060,47.395833,48.522453,55.505806,52.660880,42.033674,24.691229
76,77,5.567222,50.205503,53.882705,53.156883,60.174071,58.526326,46.839969,46.775794,47.153252,52.806594,50.832087,40.104774,24.510499
77,78,5.562507,50.554518,53.030822,52.410332,58.819961,56.988242,45.118642,45.362103,46.688240,50.282839,48.429318,39.024311,24.902006
78,79,5.685786,50.007643,50.543664,50.416451,57.198922,55.549105,43.876174,46.230159,46.528877,52.186748,50.588281,39.935966,24.332621
79,80,5.529997,51.203295,51.250000,51.689117,58.597082,56.658873,45.130568,47.048611,47.503464,53.009134,51.535402,40.285847,24.259744

## 9. Load best checkpoint and save final predictions

In [ ]:
checkpoint = torch.load(best_path, map_location=device)

best_model = MultiStageModel(
    num_stages=NUM_STAGES,
    num_layers=NUM_LAYERS,
    in_dim=feature_dim,
    num_f_maps=NUM_F_MAPS,
    num_classes=num_classes,
    dropout=DROPOUT,
).to(device)

best_model.load_state_dict(checkpoint["model_state"])

test_pred_dir = PRED_DIR / "test"
train_pred_dir = PRED_DIR / "train"

train_metrics = evaluate_model(best_model, train_loader, save_predictions=True, pred_dir=train_pred_dir)
test_metrics = evaluate_model(best_model, test_loader, save_predictions=True, pred_dir=test_pred_dir)

print("Best checkpoint epoch:", checkpoint["epoch"])
print("Train metrics:", train_metrics)
print("Test metrics:", test_metrics)

summary = {
    "run_name": RUN_NAME,
    "data_root": str(DATA_ROOT),
    "output_root": str(OUT_ROOT),
    "best_checkpoint": str(best_path),
    "best_epoch": int(checkpoint["epoch"]),
    "train_metrics": train_metrics,
    "test_metrics": test_metrics,
    "feature_dim": feature_dim,
    "feature_len": feature_len,
    "num_train_videos": len(train_ids),
    "num_test_videos": len(test_ids),
    "num_classes": num_classes,
    "note": "MS-TCN-style baseline on coarse ProcedureVRL clip-level features.",
}

summary_path = OUT_ROOT / "final_summary.json"
summary_path.write_text(json.dumps(summary, indent=2))

metrics_path = OUT_ROOT / "final_metrics.csv"
pd.DataFrame([
    {"split": "train", **train_metrics},
    {"split": "test", **test_metrics},
]).to_csv(metrics_path, index=False)

print("summary:", summary_path)
print("metrics:", metrics_path)
print(json.dumps(summary, indent=2))

Best checkpoint epoch: 69
Train metrics: {'acc': 51.81506849315068, 'edit': 52.22306442260742, 'f1@10': 59.32404999870754, 'f1@25': 57.35229021359159, 'f1@50': 44.95058670401137, 'frames': 23360, 'videos': 1460}
Test metrics: {'acc': 48.90873015873016, 'edit': 49.14902877807617, 'f1@10': 55.45678527821384, 'f1@25': 54.384011050677714, 'f1@50': 42.61379933998981, 'frames': 4032, 'videos': 252}
summary: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/final_summary.json
metrics: /content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/final_metrics.csv
{
  "run_name": "mstcn_on_procedurevrl_breakfast_full_split1",
  "data_root": "/content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/runs/procedurevrl_breakfast_full_split1_split1_views16/mstcn_format",
  "output_root": "/content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1",
  "best_checkpoint": "/content/drive/MyDrive/mmf_tas_lab_data/text_assisted_tas/breakfast/procedurevrl/mstcn_runs/mstcn_on_procedurevrl_breakfast_full_split1/checkpoints/best_model.pt",
  "best_epoch": 69,
  "train_metrics": {
    "acc": 51.81506849315068,
    "edit": 52.22306442260742,
    "f1@10": 59.32404999870754,
    "f1@25": 57.35229021359159,
    "f1@50": 44.95058670401137,
    "frames": 23360,
    "videos": 1460
  },
  "test_metrics": {
    "acc": 48.90873015873016,
    "edit": 49.14902877807617,
    "f1@10": 55.45678527821384,
    "f1@25": 54.384011050677714,
    "f1@50": 42.61379933998981,
    "frames": 4032,
    "videos": 252
  },
  "feature_dim": 9871,
  "feature_len": 16,
  "num_train_videos": 1460,
  "num_test_videos": 252,
  "num_classes": 48,
  "note": "MS-TCN-style baseline on coarse ProcedureVRL clip-level features."
}

## 10. Quick comparison with previous I3D/KD results table

In [ ]:
# Report-friendly comparison table.
# ProcedureVRL results below use coarse clip-level features with T=16.
# I3D results use frame-/segment-level features with variable temporal length T.
# Therefore this table is useful for progress reporting, but not for claiming a fully fair comparison.

def r2(x):
    return round(float(x), 2)

comparison_rows = [
    {
        "experiment": "Current experiment",
        "features": "ProcedureVRL coarse outputs",
        "model": "MS-TCN-style visual-only",
        "split": "Breakfast split 1",
        "feature_shape": f"[9871, {feature_len}]",
        "temporal_resolution": "16 clips per video",
        "acc": r2(test_metrics["acc"]),
        "edit": r2(test_metrics["edit"]),
        "f1@10": r2(test_metrics["f1@10"]),
        "f1@25": r2(test_metrics["f1@25"]),
        "f1@50": r2(test_metrics["f1@50"]),
        "directly_comparable_to_i3d": "No",
        "note": (
            "Successful ProcedureVRL -> TAS pipeline validation. "
            "Coarse clip-level outputs; not a fair frame-level comparison to I3D."
        ),
    },
    {
        "experiment": "Previous baseline",
        "features": "I3D",
        "model": "Official MS-TCN visual-only, 30 epochs",
        "split": "Breakfast split 1",
        "feature_shape": "[2048, T]",
        "temporal_resolution": "frame/segment-level variable T",
        "acc": 55.38,
        "edit": 44.97,
        "f1@10": 39.05,
        "f1@25": 34.80,
        "f1@50": 25.25,
        "directly_comparable_to_i3d": "Reference",
        "note": "Previous frame-level visual-only MS-TCN run.",
    },
    {
        "experiment": "Previous proof-of-concept",
        "features": "I3D + CLIP text teacher",
        "model": "Video-only student KD, lambda=0.05",
        "split": "Breakfast split 1",
        "feature_shape": "[2048, T]",
        "temporal_resolution": "frame/segment-level variable T",
        "acc": 70.98,
        "edit": 58.53,
        "f1@10": 50.16,
        "f1@25": 46.86,
        "f1@50": 38.33,
        "directly_comparable_to_i3d": "Yes, but text/visual spaces not aligned",
        "note": (
            "Previous KD proof-of-concept. "
            "Useful result, but visual I3D and CLIP text embeddings are not from the same latent space."
        ),
    },
]

df_comparison = pd.DataFrame(comparison_rows)

comparison_path = OUT_ROOT / "comparison_with_previous_runs.csv"
comparison_md_path = OUT_ROOT / "comparison_with_previous_runs.md"

df_comparison.to_csv(comparison_path, index=False)
comparison_md_path.write_text(df_comparison.to_markdown(index=False))

display(df_comparison)

print("saved CSV:", comparison_path)
print("saved Markdown:", comparison_md_path)

print("\nReport summary:")
print(
    f"ProcedureVRL coarse MS-TCN baseline on Breakfast split 1: "
    f"Acc={r2(test_metrics['acc'])}, "
    f"Edit={r2(test_metrics['edit'])}, "
    f"F1@10={r2(test_metrics['f1@10'])}, "
    f"F1@25={r2(test_metrics['f1@25'])}, "
    f"F1@50={r2(test_metrics['f1@50'])}."
)

print(
    "\nCaveat: these ProcedureVRL features have temporal length 16 per video, "
    "so this is a pipeline validation / preliminary baseline, not a fully fair "
    "frame-level comparison to I3D."
)